//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCM.Web.Business.ProxyBooking
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookingOverviewRepositoryInput", Namespace="http://www.tieto.com/cmw/tcm/booking")]
    public partial class BookingOverviewRepositoryInput : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private TCM.Web.Business.ProxyBooking.BookingOverviewRepository BookingOverviewRepositoryField;
        
        private TCM.Web.Business.ProxyBooking.Context InputContextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TCM.Web.Business.ProxyBooking.BookingOverviewRepository BookingOverviewRepository
        {
            get
            {
                return this.BookingOverviewRepositoryField;
            }
            set
            {
                if ((object.ReferenceEquals(this.BookingOverviewRepositoryField, value) != true))
                {
                    this.BookingOverviewRepositoryField = value;
                    this.RaisePropertyChanged("BookingOverviewRepository");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TCM.Web.Business.ProxyBooking.Context InputContext
        {
            get
            {
                return this.InputContextField;
            }
            set
            {
                if ((object.ReferenceEquals(this.InputContextField, value) != true))
                {
                    this.InputContextField = value;
                    this.RaisePropertyChanged("InputContext");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookingOverviewRepository", Namespace="http://www.tieto.com/cmw/tcm/booking")]
    public partial class BookingOverviewRepository : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private TCM.Web.Business.ProxyBooking.CriteriaOptions OptionsField;
        
        private string CriteriaTypeField;
        
        private System.Nullable<long> TotalRecordsField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyBooking.BookingOverview> BookingOverviewListField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyBooking.GeneralCriterion> SearchCriteriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TCM.Web.Business.ProxyBooking.CriteriaOptions Options
        {
            get
            {
                return this.OptionsField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OptionsField, value) != true))
                {
                    this.OptionsField = value;
                    this.RaisePropertyChanged("Options");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CriteriaType
        {
            get
            {
                return this.CriteriaTypeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CriteriaTypeField, value) != true))
                {
                    this.CriteriaTypeField = value;
                    this.RaisePropertyChanged("CriteriaType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Nullable<long> TotalRecords
        {
            get
            {
                return this.TotalRecordsField;
            }
            set
            {
                if ((this.TotalRecordsField.Equals(value) != true))
                {
                    this.TotalRecordsField = value;
                    this.RaisePropertyChanged("TotalRecords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyBooking.BookingOverview> BookingOverviewList
        {
            get
            {
                return this.BookingOverviewListField;
            }
            set
            {
                if ((object.ReferenceEquals(this.BookingOverviewListField, value) != true))
                {
                    this.BookingOverviewListField = value;
                    this.RaisePropertyChanged("BookingOverviewList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyBooking.GeneralCriterion> SearchCriteria
        {
            get
            {
                return this.SearchCriteriaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SearchCriteriaField, value) != true))
                {
                    this.SearchCriteriaField = value;
                    this.RaisePropertyChanged("SearchCriteria");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Context", Namespace="http://www.tieto.com/cmw/tcm/")]
    public partial class Context : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string ClientRowVersionField;
        
        private System.Nullable<System.DateTime> CreatedDateField;
        
        private string ExtChannelIdField;
        
        private string ExtIdField;
        
        private string ExtPosReferenceField;
        
        private string ExtUserField;
        
        private string LanguageIdField;
        
        private System.Nullable<System.DateTime> RegDateField;
        
        private string RegInterfaceField;
        
        private System.Nullable<long> RegTokenField;
        
        private string RegUserField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ClientRowVersion
        {
            get
            {
                return this.ClientRowVersionField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ClientRowVersionField, value) != true))
                {
                    this.ClientRowVersionField = value;
                    this.RaisePropertyChanged("ClientRowVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<System.DateTime> CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                if ((this.CreatedDateField.Equals(value) != true))
                {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExtChannelId
        {
            get
            {
                return this.ExtChannelIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtChannelIdField, value) != true))
                {
                    this.ExtChannelIdField = value;
                    this.RaisePropertyChanged("ExtChannelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExtId
        {
            get
            {
                return this.ExtIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtIdField, value) != true))
                {
                    this.ExtIdField = value;
                    this.RaisePropertyChanged("ExtId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExtPosReference
        {
            get
            {
                return this.ExtPosReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtPosReferenceField, value) != true))
                {
                    this.ExtPosReferenceField = value;
                    this.RaisePropertyChanged("ExtPosReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExtUser
        {
            get
            {
                return this.ExtUserField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtUserField, value) != true))
                {
                    this.ExtUserField = value;
                    this.RaisePropertyChanged("ExtUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LanguageId
        {
            get
            {
                return this.LanguageIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LanguageIdField, value) != true))
                {
                    this.LanguageIdField = value;
                    this.RaisePropertyChanged("LanguageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<System.DateTime> RegDate
        {
            get
            {
                return this.RegDateField;
            }
            set
            {
                if ((this.RegDateField.Equals(value) != true))
                {
                    this.RegDateField = value;
                    this.RaisePropertyChanged("RegDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RegInterface
        {
            get
            {
                return this.RegInterfaceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.RegInterfaceField, value) != true))
                {
                    this.RegInterfaceField = value;
                    this.RaisePropertyChanged("RegInterface");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<long> RegToken
        {
            get
            {
                return this.RegTokenField;
            }
            set
            {
                if ((this.RegTokenField.Equals(value) != true))
                {
                    this.RegTokenField = value;
                    this.RaisePropertyChanged("RegToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RegUser
        {
            get
            {
                return this.RegUserField;
            }
            set
            {
                if ((object.ReferenceEquals(this.RegUserField, value) != true))
                {
                    this.RegUserField = value;
                    this.RaisePropertyChanged("RegUser");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CriteriaOptions", Namespace="http://www.tieto.com/cmw/tcm/booking")]
    public partial class CriteriaOptions : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private System.Nullable<bool> ShowActiveField;
        
        private System.Nullable<bool> ShowInactiveField;
        
        private System.Nullable<long> BrowseFromField;
        
        private System.Nullable<long> BrowseToField;
        
        private string SortFieldField;
        
        private string SortOrderField;
        
        private System.Nullable<bool> CaseSensitiveField;
        
        private string ExtPosReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<bool> ShowActive
        {
            get
            {
                return this.ShowActiveField;
            }
            set
            {
                if ((this.ShowActiveField.Equals(value) != true))
                {
                    this.ShowActiveField = value;
                    this.RaisePropertyChanged("ShowActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<bool> ShowInactive
        {
            get
            {
                return this.ShowInactiveField;
            }
            set
            {
                if ((this.ShowInactiveField.Equals(value) != true))
                {
                    this.ShowInactiveField = value;
                    this.RaisePropertyChanged("ShowInactive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Nullable<long> BrowseFrom
        {
            get
            {
                return this.BrowseFromField;
            }
            set
            {
                if ((this.BrowseFromField.Equals(value) != true))
                {
                    this.BrowseFromField = value;
                    this.RaisePropertyChanged("BrowseFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Nullable<long> BrowseTo
        {
            get
            {
                return this.BrowseToField;
            }
            set
            {
                if ((this.BrowseToField.Equals(value) != true))
                {
                    this.BrowseToField = value;
                    this.RaisePropertyChanged("BrowseTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SortField
        {
            get
            {
                return this.SortFieldField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SortFieldField, value) != true))
                {
                    this.SortFieldField = value;
                    this.RaisePropertyChanged("SortField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SortOrder
        {
            get
            {
                return this.SortOrderField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SortOrderField, value) != true))
                {
                    this.SortOrderField = value;
                    this.RaisePropertyChanged("SortOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public System.Nullable<bool> CaseSensitive
        {
            get
            {
                return this.CaseSensitiveField;
            }
            set
            {
                if ((this.CaseSensitiveField.Equals(value) != true))
                {
                    this.CaseSensitiveField = value;
                    this.RaisePropertyChanged("CaseSensitive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ExtPosReference
        {
            get
            {
                return this.ExtPosReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtPosReferenceField, value) != true))
                {
                    this.ExtPosReferenceField = value;
                    this.RaisePropertyChanged("ExtPosReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookingOverview", Namespace="http://www.tieto.com/cmw/tcm/booking")]
    public partial class BookingOverview : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private System.Nullable<long> DepositReferenceIdField;
        
        private string EntityCodeField;
        
        private System.Nullable<long> EntityIdField;
        
        private string BatchIdField;
        
        private System.Nullable<long> BookingMovementIdField;
        
        private System.Nullable<int> BookingGroupIdField;
        
        private string BookingDirectionField;
        
        private string AccountNumberField;
        
        private System.Nullable<decimal> AmountField;
        
        private string CurrencyIdField;
        
        private System.Nullable<System.DateTime> ValueDateField;
        
        private string ExtReferenceField;
        
        private System.Nullable<System.DateTime> ProcessingDateField;
        
        private System.Nullable<bool> IsExportedField;
        
        private string StatusCodeField;
        
        private string StatusReferenceField;
        
        private string NoteField;
        
        private string ExtPosReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<long> DepositReferenceId
        {
            get
            {
                return this.DepositReferenceIdField;
            }
            set
            {
                if ((this.DepositReferenceIdField.Equals(value) != true))
                {
                    this.DepositReferenceIdField = value;
                    this.RaisePropertyChanged("DepositReferenceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EntityCode
        {
            get
            {
                return this.EntityCodeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.EntityCodeField, value) != true))
                {
                    this.EntityCodeField = value;
                    this.RaisePropertyChanged("EntityCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<long> EntityId
        {
            get
            {
                return this.EntityIdField;
            }
            set
            {
                if ((this.EntityIdField.Equals(value) != true))
                {
                    this.EntityIdField = value;
                    this.RaisePropertyChanged("EntityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string BatchId
        {
            get
            {
                return this.BatchIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.BatchIdField, value) != true))
                {
                    this.BatchIdField = value;
                    this.RaisePropertyChanged("BatchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public System.Nullable<long> BookingMovementId
        {
            get
            {
                return this.BookingMovementIdField;
            }
            set
            {
                if ((this.BookingMovementIdField.Equals(value) != true))
                {
                    this.BookingMovementIdField = value;
                    this.RaisePropertyChanged("BookingMovementId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public System.Nullable<int> BookingGroupId
        {
            get
            {
                return this.BookingGroupIdField;
            }
            set
            {
                if ((this.BookingGroupIdField.Equals(value) != true))
                {
                    this.BookingGroupIdField = value;
                    this.RaisePropertyChanged("BookingGroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string BookingDirection
        {
            get
            {
                return this.BookingDirectionField;
            }
            set
            {
                if ((object.ReferenceEquals(this.BookingDirectionField, value) != true))
                {
                    this.BookingDirectionField = value;
                    this.RaisePropertyChanged("BookingDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string AccountNumber
        {
            get
            {
                return this.AccountNumberField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true))
                {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public System.Nullable<decimal> Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                if ((this.AmountField.Equals(value) != true))
                {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string CurrencyId
        {
            get
            {
                return this.CurrencyIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CurrencyIdField, value) != true))
                {
                    this.CurrencyIdField = value;
                    this.RaisePropertyChanged("CurrencyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public System.Nullable<System.DateTime> ValueDate
        {
            get
            {
                return this.ValueDateField;
            }
            set
            {
                if ((this.ValueDateField.Equals(value) != true))
                {
                    this.ValueDateField = value;
                    this.RaisePropertyChanged("ValueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string ExtReference
        {
            get
            {
                return this.ExtReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtReferenceField, value) != true))
                {
                    this.ExtReferenceField = value;
                    this.RaisePropertyChanged("ExtReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public System.Nullable<System.DateTime> ProcessingDate
        {
            get
            {
                return this.ProcessingDateField;
            }
            set
            {
                if ((this.ProcessingDateField.Equals(value) != true))
                {
                    this.ProcessingDateField = value;
                    this.RaisePropertyChanged("ProcessingDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public System.Nullable<bool> IsExported
        {
            get
            {
                return this.IsExportedField;
            }
            set
            {
                if ((this.IsExportedField.Equals(value) != true))
                {
                    this.IsExportedField = value;
                    this.RaisePropertyChanged("IsExported");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.StatusCodeField, value) != true))
                {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string StatusReference
        {
            get
            {
                return this.StatusReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.StatusReferenceField, value) != true))
                {
                    this.StatusReferenceField = value;
                    this.RaisePropertyChanged("StatusReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Note
        {
            get
            {
                return this.NoteField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NoteField, value) != true))
                {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string ExtPosReference
        {
            get
            {
                return this.ExtPosReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtPosReferenceField, value) != true))
                {
                    this.ExtPosReferenceField = value;
                    this.RaisePropertyChanged("ExtPosReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneralCriterion", Namespace="http://www.tieto.com/cmw/tcm/booking")]
    public partial class GeneralCriterion : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string SearchConcatenatorIdField;
        
        private string SearchFieldIdField;
        
        private string SearchOperatorIdField;
        
        private string SearchValueField;
        
        private string ExtPosReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SearchConcatenatorId
        {
            get
            {
                return this.SearchConcatenatorIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SearchConcatenatorIdField, value) != true))
                {
                    this.SearchConcatenatorIdField = value;
                    this.RaisePropertyChanged("SearchConcatenatorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SearchFieldId
        {
            get
            {
                return this.SearchFieldIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SearchFieldIdField, value) != true))
                {
                    this.SearchFieldIdField = value;
                    this.RaisePropertyChanged("SearchFieldId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SearchOperatorId
        {
            get
            {
                return this.SearchOperatorIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SearchOperatorIdField, value) != true))
                {
                    this.SearchOperatorIdField = value;
                    this.RaisePropertyChanged("SearchOperatorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SearchValue
        {
            get
            {
                return this.SearchValueField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SearchValueField, value) != true))
                {
                    this.SearchValueField = value;
                    this.RaisePropertyChanged("SearchValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ExtPosReference
        {
            get
            {
                return this.ExtPosReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtPosReferenceField, value) != true))
                {
                    this.ExtPosReferenceField = value;
                    this.RaisePropertyChanged("ExtPosReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookingOverviewRepositoryOutput", Namespace="http://www.tieto.com/cmw/tcm/booking")]
    public partial class BookingOverviewRepositoryOutput : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private bool SuccessField;
        
        private TCM.Web.Business.ProxyBooking.BookingOverviewRepository BookingOverviewRepositoryField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyBooking.Error> ErrorListField;
        
        private TCM.Web.Business.ProxyBooking.Context OutputContextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                if ((this.SuccessField.Equals(value) != true))
                {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public TCM.Web.Business.ProxyBooking.BookingOverviewRepository BookingOverviewRepository
        {
            get
            {
                return this.BookingOverviewRepositoryField;
            }
            set
            {
                if ((object.ReferenceEquals(this.BookingOverviewRepositoryField, value) != true))
                {
                    this.BookingOverviewRepositoryField = value;
                    this.RaisePropertyChanged("BookingOverviewRepository");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyBooking.Error> ErrorList
        {
            get
            {
                return this.ErrorListField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorListField, value) != true))
                {
                    this.ErrorListField = value;
                    this.RaisePropertyChanged("ErrorList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public TCM.Web.Business.ProxyBooking.Context OutputContext
        {
            get
            {
                return this.OutputContextField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OutputContextField, value) != true))
                {
                    this.OutputContextField = value;
                    this.RaisePropertyChanged("OutputContext");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://www.tieto.com/cmw/tcm/")]
    public partial class Error : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string ErrorCodeField;
        
        private string ErrorMessageField;
        
        private string ExtErrorPosReferenceField;
        
        private string SystemErrorMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true))
                {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true))
                {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtErrorPosReference
        {
            get
            {
                return this.ExtErrorPosReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtErrorPosReferenceField, value) != true))
                {
                    this.ExtErrorPosReferenceField = value;
                    this.RaisePropertyChanged("ExtErrorPosReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SystemErrorMessage
        {
            get
            {
                return this.SystemErrorMessageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SystemErrorMessageField, value) != true))
                {
                    this.SystemErrorMessageField = value;
                    this.RaisePropertyChanged("SystemErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.tieto.com/cmw/tcm/booking", ConfigurationName="TCM.Web.Business.ProxyBooking.IWSBooking")]
    public interface IWSBooking
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tieto.com/cmw/tcm/booking/IWSBooking/BookingOverviewFind", ReplyAction="http://www.tieto.com/cmw/tcm/booking/IWSBooking/BookingOverviewFindResponse")]
        System.Threading.Tasks.Task<TCM.Web.Business.ProxyBooking.BookingOverviewRepositoryOutput> BookingOverviewFindAsync(TCM.Web.Business.ProxyBooking.BookingOverviewRepositoryInput inputDTO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public interface IWSBookingChannel : TCM.Web.Business.ProxyBooking.IWSBooking, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public partial class WSBookingClient : System.ServiceModel.ClientBase<TCM.Web.Business.ProxyBooking.IWSBooking>, TCM.Web.Business.ProxyBooking.IWSBooking
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSBookingClient() : 
                base(WSBookingClient.GetDefaultBinding(), WSBookingClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IWSBooking.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSBookingClient(EndpointConfiguration endpointConfiguration) : 
                base(WSBookingClient.GetBindingForEndpoint(endpointConfiguration), WSBookingClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSBookingClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSBookingClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSBookingClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSBookingClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSBookingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<TCM.Web.Business.ProxyBooking.BookingOverviewRepositoryOutput> BookingOverviewFindAsync(TCM.Web.Business.ProxyBooking.BookingOverviewRepositoryInput inputDTO)
        {
            return base.Channel.BookingOverviewFindAsync(inputDTO);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWSBooking))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWSBooking))
            {
                return new System.ServiceModel.EndpointAddress("http://tcmrobur2012.bise.financialsolutions.se:801/WSBooking.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WSBookingClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IWSBooking);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WSBookingClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IWSBooking);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IWSBooking,
        }
    }
}
