//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCM.Web.Business.ProxyNLuxHolder
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HolderInput", Namespace="http://www.tieto.com/cmw/tcm/holder")]
    public partial class HolderInput : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private TCM.Web.Business.ProxyNLuxHolder.Holder HolderField;
        
        private TCM.Web.Business.ProxyNLuxHolder.Context InputContextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TCM.Web.Business.ProxyNLuxHolder.Holder Holder
        {
            get
            {
                return this.HolderField;
            }
            set
            {
                if ((object.ReferenceEquals(this.HolderField, value) != true))
                {
                    this.HolderField = value;
                    this.RaisePropertyChanged("Holder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TCM.Web.Business.ProxyNLuxHolder.Context InputContext
        {
            get
            {
                return this.InputContextField;
            }
            set
            {
                if ((object.ReferenceEquals(this.InputContextField, value) != true))
                {
                    this.InputContextField = value;
                    this.RaisePropertyChanged("InputContext");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Holder", Namespace="http://www.tieto.com/cmw/tcm/holder")]
    public partial class Holder : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private TCM.Web.Business.ProxyNLuxHolder.HolderIdentity IdentityField;
        
        private TCM.Web.Business.ProxyNLuxHolder.OrganizationIdentity CustomerAdministratorField;
        
        private string ObjectVersionField;
        
        private string TINField;
        
        private string TINIssuingCountryIdField;
        
        private string TINIssuingCountryNameField;
        
        private string GIINField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyNLuxHolder.BeneficialOwner> BeneficialOwnerListField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TCM.Web.Business.ProxyNLuxHolder.HolderIdentity Identity
        {
            get
            {
                return this.IdentityField;
            }
            set
            {
                if ((object.ReferenceEquals(this.IdentityField, value) != true))
                {
                    this.IdentityField = value;
                    this.RaisePropertyChanged("Identity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public TCM.Web.Business.ProxyNLuxHolder.OrganizationIdentity CustomerAdministrator
        {
            get
            {
                return this.CustomerAdministratorField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CustomerAdministratorField, value) != true))
                {
                    this.CustomerAdministratorField = value;
                    this.RaisePropertyChanged("CustomerAdministrator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ObjectVersion
        {
            get
            {
                return this.ObjectVersionField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ObjectVersionField, value) != true))
                {
                    this.ObjectVersionField = value;
                    this.RaisePropertyChanged("ObjectVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TIN
        {
            get
            {
                return this.TINField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TINField, value) != true))
                {
                    this.TINField = value;
                    this.RaisePropertyChanged("TIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TINIssuingCountryId
        {
            get
            {
                return this.TINIssuingCountryIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TINIssuingCountryIdField, value) != true))
                {
                    this.TINIssuingCountryIdField = value;
                    this.RaisePropertyChanged("TINIssuingCountryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string TINIssuingCountryName
        {
            get
            {
                return this.TINIssuingCountryNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TINIssuingCountryNameField, value) != true))
                {
                    this.TINIssuingCountryNameField = value;
                    this.RaisePropertyChanged("TINIssuingCountryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string GIIN
        {
            get
            {
                return this.GIINField;
            }
            set
            {
                if ((object.ReferenceEquals(this.GIINField, value) != true))
                {
                    this.GIINField = value;
                    this.RaisePropertyChanged("GIIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyNLuxHolder.BeneficialOwner> BeneficialOwnerList
        {
            get
            {
                return this.BeneficialOwnerListField;
            }
            set
            {
                if ((object.ReferenceEquals(this.BeneficialOwnerListField, value) != true))
                {
                    this.BeneficialOwnerListField = value;
                    this.RaisePropertyChanged("BeneficialOwnerList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Context", Namespace="http://www.tieto.com/cmw/tcm/")]
    public partial class Context : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string ClientRowVersionField;
        
        private System.Nullable<System.DateTime> CreatedDateField;
        
        private string ExtChannelIdField;
        
        private string ExtIdField;
        
        private string ExtPosReferenceField;
        
        private string ExtUserField;
        
        private string LanguageIdField;
        
        private System.Nullable<System.DateTime> RegDateField;
        
        private string RegInterfaceField;
        
        private System.Nullable<long> RegTokenField;
        
        private string RegUserField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ClientRowVersion
        {
            get
            {
                return this.ClientRowVersionField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ClientRowVersionField, value) != true))
                {
                    this.ClientRowVersionField = value;
                    this.RaisePropertyChanged("ClientRowVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<System.DateTime> CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                if ((this.CreatedDateField.Equals(value) != true))
                {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExtChannelId
        {
            get
            {
                return this.ExtChannelIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtChannelIdField, value) != true))
                {
                    this.ExtChannelIdField = value;
                    this.RaisePropertyChanged("ExtChannelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExtId
        {
            get
            {
                return this.ExtIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtIdField, value) != true))
                {
                    this.ExtIdField = value;
                    this.RaisePropertyChanged("ExtId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExtPosReference
        {
            get
            {
                return this.ExtPosReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtPosReferenceField, value) != true))
                {
                    this.ExtPosReferenceField = value;
                    this.RaisePropertyChanged("ExtPosReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExtUser
        {
            get
            {
                return this.ExtUserField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtUserField, value) != true))
                {
                    this.ExtUserField = value;
                    this.RaisePropertyChanged("ExtUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LanguageId
        {
            get
            {
                return this.LanguageIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LanguageIdField, value) != true))
                {
                    this.LanguageIdField = value;
                    this.RaisePropertyChanged("LanguageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<System.DateTime> RegDate
        {
            get
            {
                return this.RegDateField;
            }
            set
            {
                if ((this.RegDateField.Equals(value) != true))
                {
                    this.RegDateField = value;
                    this.RaisePropertyChanged("RegDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RegInterface
        {
            get
            {
                return this.RegInterfaceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.RegInterfaceField, value) != true))
                {
                    this.RegInterfaceField = value;
                    this.RaisePropertyChanged("RegInterface");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<long> RegToken
        {
            get
            {
                return this.RegTokenField;
            }
            set
            {
                if ((this.RegTokenField.Equals(value) != true))
                {
                    this.RegTokenField = value;
                    this.RaisePropertyChanged("RegToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RegUser
        {
            get
            {
                return this.RegUserField;
            }
            set
            {
                if ((object.ReferenceEquals(this.RegUserField, value) != true))
                {
                    this.RegUserField = value;
                    this.RaisePropertyChanged("RegUser");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HolderIdentity", Namespace="http://www.tieto.com/cmw/tcm/holder")]
    public partial class HolderIdentity : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private TCM.Web.Business.ProxyNLuxHolder.OrganizationIdentity CustomerAdministratorField;
        
        private string ExternalHolderIdField;
        
        private string IdentificationIdField;
        
        private string NationalRegistrationIdField;
        
        private string IdCoordinatesField;
        
        private string GenericIdentifierCodeField;
        
        private string GenericIdentifierValueField;
        
        private System.Nullable<long> HolderIdField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private string OfficialNameField;
        
        private string OrganizationLongNameField;
        
        private string OrganizationNameField;
        
        private string ExtPosReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TCM.Web.Business.ProxyNLuxHolder.OrganizationIdentity CustomerAdministrator
        {
            get
            {
                return this.CustomerAdministratorField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CustomerAdministratorField, value) != true))
                {
                    this.CustomerAdministratorField = value;
                    this.RaisePropertyChanged("CustomerAdministrator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExternalHolderId
        {
            get
            {
                return this.ExternalHolderIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExternalHolderIdField, value) != true))
                {
                    this.ExternalHolderIdField = value;
                    this.RaisePropertyChanged("ExternalHolderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IdentificationId
        {
            get
            {
                return this.IdentificationIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.IdentificationIdField, value) != true))
                {
                    this.IdentificationIdField = value;
                    this.RaisePropertyChanged("IdentificationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NationalRegistrationId
        {
            get
            {
                return this.NationalRegistrationIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NationalRegistrationIdField, value) != true))
                {
                    this.NationalRegistrationIdField = value;
                    this.RaisePropertyChanged("NationalRegistrationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string IdCoordinates
        {
            get
            {
                return this.IdCoordinatesField;
            }
            set
            {
                if ((object.ReferenceEquals(this.IdCoordinatesField, value) != true))
                {
                    this.IdCoordinatesField = value;
                    this.RaisePropertyChanged("IdCoordinates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string GenericIdentifierCode
        {
            get
            {
                return this.GenericIdentifierCodeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.GenericIdentifierCodeField, value) != true))
                {
                    this.GenericIdentifierCodeField = value;
                    this.RaisePropertyChanged("GenericIdentifierCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string GenericIdentifierValue
        {
            get
            {
                return this.GenericIdentifierValueField;
            }
            set
            {
                if ((object.ReferenceEquals(this.GenericIdentifierValueField, value) != true))
                {
                    this.GenericIdentifierValueField = value;
                    this.RaisePropertyChanged("GenericIdentifierValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public System.Nullable<long> HolderId
        {
            get
            {
                return this.HolderIdField;
            }
            set
            {
                if ((this.HolderIdField.Equals(value) != true))
                {
                    this.HolderIdField = value;
                    this.RaisePropertyChanged("HolderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true))
                {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LastNameField, value) != true))
                {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string OfficialName
        {
            get
            {
                return this.OfficialNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OfficialNameField, value) != true))
                {
                    this.OfficialNameField = value;
                    this.RaisePropertyChanged("OfficialName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string OrganizationLongName
        {
            get
            {
                return this.OrganizationLongNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OrganizationLongNameField, value) != true))
                {
                    this.OrganizationLongNameField = value;
                    this.RaisePropertyChanged("OrganizationLongName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string OrganizationName
        {
            get
            {
                return this.OrganizationNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OrganizationNameField, value) != true))
                {
                    this.OrganizationNameField = value;
                    this.RaisePropertyChanged("OrganizationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string ExtPosReference
        {
            get
            {
                return this.ExtPosReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtPosReferenceField, value) != true))
                {
                    this.ExtPosReferenceField = value;
                    this.RaisePropertyChanged("ExtPosReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrganizationIdentity", Namespace="http://www.tieto.com/cmw/tcm/holder")]
    public partial class OrganizationIdentity : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private System.Nullable<int> OrganizationIdField;
        
        private string ExternalOrganizationIdField;
        
        private string NationalRegistrationIdField;
        
        private string OrganizationShortNameField;
        
        private string OrganizationNameField;
        
        private string OrganizationLongNameField;
        
        private string ExtPosReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<int> OrganizationId
        {
            get
            {
                return this.OrganizationIdField;
            }
            set
            {
                if ((this.OrganizationIdField.Equals(value) != true))
                {
                    this.OrganizationIdField = value;
                    this.RaisePropertyChanged("OrganizationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ExternalOrganizationId
        {
            get
            {
                return this.ExternalOrganizationIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExternalOrganizationIdField, value) != true))
                {
                    this.ExternalOrganizationIdField = value;
                    this.RaisePropertyChanged("ExternalOrganizationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NationalRegistrationId
        {
            get
            {
                return this.NationalRegistrationIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NationalRegistrationIdField, value) != true))
                {
                    this.NationalRegistrationIdField = value;
                    this.RaisePropertyChanged("NationalRegistrationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string OrganizationShortName
        {
            get
            {
                return this.OrganizationShortNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OrganizationShortNameField, value) != true))
                {
                    this.OrganizationShortNameField = value;
                    this.RaisePropertyChanged("OrganizationShortName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string OrganizationName
        {
            get
            {
                return this.OrganizationNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OrganizationNameField, value) != true))
                {
                    this.OrganizationNameField = value;
                    this.RaisePropertyChanged("OrganizationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string OrganizationLongName
        {
            get
            {
                return this.OrganizationLongNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OrganizationLongNameField, value) != true))
                {
                    this.OrganizationLongNameField = value;
                    this.RaisePropertyChanged("OrganizationLongName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ExtPosReference
        {
            get
            {
                return this.ExtPosReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtPosReferenceField, value) != true))
                {
                    this.ExtPosReferenceField = value;
                    this.RaisePropertyChanged("ExtPosReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BeneficialOwner", Namespace="http://www.tieto.com/cmw/tcm/holder")]
    public partial class BeneficialOwner : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private System.Nullable<long> BeneficialOwnerIdField;
        
        private System.Nullable<long> BeneficialOwnerHolderIdField;
        
        private string NationalRegistrationIdField;
        
        private string IdentificationIdField;
        
        private System.Nullable<decimal> PercentageOfOwnershipField;
        
        private System.Nullable<bool> IsExistingHolderField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private string DistributionAddress1Field;
        
        private string DistributionAddress2Field;
        
        private string PostalCodeIdField;
        
        private string CityNameField;
        
        private string StateNameField;
        
        private string CountryIdField;
        
        private string CountryNameField;
        
        private System.Nullable<System.DateTime> BirthDayField;
        
        private string TinField;
        
        private string TINIssuingCountryIdField;
        
        private string TINIssuingCountryNameField;
        
        private string OrganizationNameField;
        
        private System.Nullable<bool> IsPublicOfficerField;
        
        private System.Nullable<System.DateTime> CreatedDateField;
        
        private string RegUserField;
        
        private string ObjectVersionField;
        
        private string TaxCountryIdField;
        
        private string TaxCountryNameField;
        
        private string PlaceOfBirthField;
        
        private string CountryOfBirthIdField;
        
        private string CountryNameOfBirthField;
        
        private string OECDCRSControllingPersonTypeCodeField;
        
        private string OECDCRSControllingPersonTypeCodeNameField;
        
        private string ExtPosReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<long> BeneficialOwnerId
        {
            get
            {
                return this.BeneficialOwnerIdField;
            }
            set
            {
                if ((this.BeneficialOwnerIdField.Equals(value) != true))
                {
                    this.BeneficialOwnerIdField = value;
                    this.RaisePropertyChanged("BeneficialOwnerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Nullable<long> BeneficialOwnerHolderId
        {
            get
            {
                return this.BeneficialOwnerHolderIdField;
            }
            set
            {
                if ((this.BeneficialOwnerHolderIdField.Equals(value) != true))
                {
                    this.BeneficialOwnerHolderIdField = value;
                    this.RaisePropertyChanged("BeneficialOwnerHolderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NationalRegistrationId
        {
            get
            {
                return this.NationalRegistrationIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NationalRegistrationIdField, value) != true))
                {
                    this.NationalRegistrationIdField = value;
                    this.RaisePropertyChanged("NationalRegistrationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string IdentificationId
        {
            get
            {
                return this.IdentificationIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.IdentificationIdField, value) != true))
                {
                    this.IdentificationIdField = value;
                    this.RaisePropertyChanged("IdentificationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public System.Nullable<decimal> PercentageOfOwnership
        {
            get
            {
                return this.PercentageOfOwnershipField;
            }
            set
            {
                if ((this.PercentageOfOwnershipField.Equals(value) != true))
                {
                    this.PercentageOfOwnershipField = value;
                    this.RaisePropertyChanged("PercentageOfOwnership");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public System.Nullable<bool> IsExistingHolder
        {
            get
            {
                return this.IsExistingHolderField;
            }
            set
            {
                if ((this.IsExistingHolderField.Equals(value) != true))
                {
                    this.IsExistingHolderField = value;
                    this.RaisePropertyChanged("IsExistingHolder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true))
                {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LastNameField, value) != true))
                {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string DistributionAddress1
        {
            get
            {
                return this.DistributionAddress1Field;
            }
            set
            {
                if ((object.ReferenceEquals(this.DistributionAddress1Field, value) != true))
                {
                    this.DistributionAddress1Field = value;
                    this.RaisePropertyChanged("DistributionAddress1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string DistributionAddress2
        {
            get
            {
                return this.DistributionAddress2Field;
            }
            set
            {
                if ((object.ReferenceEquals(this.DistributionAddress2Field, value) != true))
                {
                    this.DistributionAddress2Field = value;
                    this.RaisePropertyChanged("DistributionAddress2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string PostalCodeId
        {
            get
            {
                return this.PostalCodeIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PostalCodeIdField, value) != true))
                {
                    this.PostalCodeIdField = value;
                    this.RaisePropertyChanged("PostalCodeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string CityName
        {
            get
            {
                return this.CityNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CityNameField, value) != true))
                {
                    this.CityNameField = value;
                    this.RaisePropertyChanged("CityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string StateName
        {
            get
            {
                return this.StateNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.StateNameField, value) != true))
                {
                    this.StateNameField = value;
                    this.RaisePropertyChanged("StateName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string CountryId
        {
            get
            {
                return this.CountryIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CountryIdField, value) != true))
                {
                    this.CountryIdField = value;
                    this.RaisePropertyChanged("CountryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string CountryName
        {
            get
            {
                return this.CountryNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CountryNameField, value) != true))
                {
                    this.CountryNameField = value;
                    this.RaisePropertyChanged("CountryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public System.Nullable<System.DateTime> BirthDay
        {
            get
            {
                return this.BirthDayField;
            }
            set
            {
                if ((this.BirthDayField.Equals(value) != true))
                {
                    this.BirthDayField = value;
                    this.RaisePropertyChanged("BirthDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Tin
        {
            get
            {
                return this.TinField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TinField, value) != true))
                {
                    this.TinField = value;
                    this.RaisePropertyChanged("Tin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string TINIssuingCountryId
        {
            get
            {
                return this.TINIssuingCountryIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TINIssuingCountryIdField, value) != true))
                {
                    this.TINIssuingCountryIdField = value;
                    this.RaisePropertyChanged("TINIssuingCountryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string TINIssuingCountryName
        {
            get
            {
                return this.TINIssuingCountryNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TINIssuingCountryNameField, value) != true))
                {
                    this.TINIssuingCountryNameField = value;
                    this.RaisePropertyChanged("TINIssuingCountryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string OrganizationName
        {
            get
            {
                return this.OrganizationNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OrganizationNameField, value) != true))
                {
                    this.OrganizationNameField = value;
                    this.RaisePropertyChanged("OrganizationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public System.Nullable<bool> IsPublicOfficer
        {
            get
            {
                return this.IsPublicOfficerField;
            }
            set
            {
                if ((this.IsPublicOfficerField.Equals(value) != true))
                {
                    this.IsPublicOfficerField = value;
                    this.RaisePropertyChanged("IsPublicOfficer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public System.Nullable<System.DateTime> CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                if ((this.CreatedDateField.Equals(value) != true))
                {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string RegUser
        {
            get
            {
                return this.RegUserField;
            }
            set
            {
                if ((object.ReferenceEquals(this.RegUserField, value) != true))
                {
                    this.RegUserField = value;
                    this.RaisePropertyChanged("RegUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string ObjectVersion
        {
            get
            {
                return this.ObjectVersionField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ObjectVersionField, value) != true))
                {
                    this.ObjectVersionField = value;
                    this.RaisePropertyChanged("ObjectVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string TaxCountryId
        {
            get
            {
                return this.TaxCountryIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TaxCountryIdField, value) != true))
                {
                    this.TaxCountryIdField = value;
                    this.RaisePropertyChanged("TaxCountryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string TaxCountryName
        {
            get
            {
                return this.TaxCountryNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TaxCountryNameField, value) != true))
                {
                    this.TaxCountryNameField = value;
                    this.RaisePropertyChanged("TaxCountryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string PlaceOfBirth
        {
            get
            {
                return this.PlaceOfBirthField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PlaceOfBirthField, value) != true))
                {
                    this.PlaceOfBirthField = value;
                    this.RaisePropertyChanged("PlaceOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string CountryOfBirthId
        {
            get
            {
                return this.CountryOfBirthIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CountryOfBirthIdField, value) != true))
                {
                    this.CountryOfBirthIdField = value;
                    this.RaisePropertyChanged("CountryOfBirthId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string CountryNameOfBirth
        {
            get
            {
                return this.CountryNameOfBirthField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CountryNameOfBirthField, value) != true))
                {
                    this.CountryNameOfBirthField = value;
                    this.RaisePropertyChanged("CountryNameOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string OECDCRSControllingPersonTypeCode
        {
            get
            {
                return this.OECDCRSControllingPersonTypeCodeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OECDCRSControllingPersonTypeCodeField, value) != true))
                {
                    this.OECDCRSControllingPersonTypeCodeField = value;
                    this.RaisePropertyChanged("OECDCRSControllingPersonTypeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public string OECDCRSControllingPersonTypeCodeName
        {
            get
            {
                return this.OECDCRSControllingPersonTypeCodeNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OECDCRSControllingPersonTypeCodeNameField, value) != true))
                {
                    this.OECDCRSControllingPersonTypeCodeNameField = value;
                    this.RaisePropertyChanged("OECDCRSControllingPersonTypeCodeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public string ExtPosReference
        {
            get
            {
                return this.ExtPosReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtPosReferenceField, value) != true))
                {
                    this.ExtPosReferenceField = value;
                    this.RaisePropertyChanged("ExtPosReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HolderOutput", Namespace="http://www.tieto.com/cmw/tcm/holder")]
    public partial class HolderOutput : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private bool SuccessField;
        
        private TCM.Web.Business.ProxyNLuxHolder.Holder HolderField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyNLuxHolder.Error> ErrorListField;
        
        private TCM.Web.Business.ProxyNLuxHolder.Context OutputContextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                if ((this.SuccessField.Equals(value) != true))
                {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public TCM.Web.Business.ProxyNLuxHolder.Holder Holder
        {
            get
            {
                return this.HolderField;
            }
            set
            {
                if ((object.ReferenceEquals(this.HolderField, value) != true))
                {
                    this.HolderField = value;
                    this.RaisePropertyChanged("Holder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyNLuxHolder.Error> ErrorList
        {
            get
            {
                return this.ErrorListField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorListField, value) != true))
                {
                    this.ErrorListField = value;
                    this.RaisePropertyChanged("ErrorList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public TCM.Web.Business.ProxyNLuxHolder.Context OutputContext
        {
            get
            {
                return this.OutputContextField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OutputContextField, value) != true))
                {
                    this.OutputContextField = value;
                    this.RaisePropertyChanged("OutputContext");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://www.tieto.com/cmw/tcm/")]
    public partial class Error : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string ErrorCodeField;
        
        private string ErrorMessageField;
        
        private string ExtErrorPosReferenceField;
        
        private string SystemErrorMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true))
                {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true))
                {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtErrorPosReference
        {
            get
            {
                return this.ExtErrorPosReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtErrorPosReferenceField, value) != true))
                {
                    this.ExtErrorPosReferenceField = value;
                    this.RaisePropertyChanged("ExtErrorPosReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SystemErrorMessage
        {
            get
            {
                return this.SystemErrorMessageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SystemErrorMessageField, value) != true))
                {
                    this.SystemErrorMessageField = value;
                    this.RaisePropertyChanged("SystemErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HolderRepositoryInput", Namespace="http://www.tieto.com/cmw/tcm/holder")]
    public partial class HolderRepositoryInput : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private TCM.Web.Business.ProxyNLuxHolder.HolderRepository HolderRepositoryField;
        
        private TCM.Web.Business.ProxyNLuxHolder.Context InputContextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TCM.Web.Business.ProxyNLuxHolder.HolderRepository HolderRepository
        {
            get
            {
                return this.HolderRepositoryField;
            }
            set
            {
                if ((object.ReferenceEquals(this.HolderRepositoryField, value) != true))
                {
                    this.HolderRepositoryField = value;
                    this.RaisePropertyChanged("HolderRepository");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TCM.Web.Business.ProxyNLuxHolder.Context InputContext
        {
            get
            {
                return this.InputContextField;
            }
            set
            {
                if ((object.ReferenceEquals(this.InputContextField, value) != true))
                {
                    this.InputContextField = value;
                    this.RaisePropertyChanged("InputContext");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HolderRepository", Namespace="http://www.tieto.com/cmw/tcm/holder")]
    public partial class HolderRepository : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private TCM.Web.Business.ProxyNLuxHolder.CriteriaOptions OptionsField;
        
        private string CriteriaTypeField;
        
        private System.Nullable<long> TotalRecordsField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyNLuxHolder.Holder> HolderListField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyNLuxHolder.GeneralCriterion> SearchCriteriaField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyNLuxHolder.SimpleCriterion> ListCriteriaField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyNLuxHolder.HolderIdentity> IdentityCriteriaField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyNLuxHolder.OrganizationIdentity> CustomerAdministratorCriteriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TCM.Web.Business.ProxyNLuxHolder.CriteriaOptions Options
        {
            get
            {
                return this.OptionsField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OptionsField, value) != true))
                {
                    this.OptionsField = value;
                    this.RaisePropertyChanged("Options");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CriteriaType
        {
            get
            {
                return this.CriteriaTypeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CriteriaTypeField, value) != true))
                {
                    this.CriteriaTypeField = value;
                    this.RaisePropertyChanged("CriteriaType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Nullable<long> TotalRecords
        {
            get
            {
                return this.TotalRecordsField;
            }
            set
            {
                if ((this.TotalRecordsField.Equals(value) != true))
                {
                    this.TotalRecordsField = value;
                    this.RaisePropertyChanged("TotalRecords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyNLuxHolder.Holder> HolderList
        {
            get
            {
                return this.HolderListField;
            }
            set
            {
                if ((object.ReferenceEquals(this.HolderListField, value) != true))
                {
                    this.HolderListField = value;
                    this.RaisePropertyChanged("HolderList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyNLuxHolder.GeneralCriterion> SearchCriteria
        {
            get
            {
                return this.SearchCriteriaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SearchCriteriaField, value) != true))
                {
                    this.SearchCriteriaField = value;
                    this.RaisePropertyChanged("SearchCriteria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyNLuxHolder.SimpleCriterion> ListCriteria
        {
            get
            {
                return this.ListCriteriaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ListCriteriaField, value) != true))
                {
                    this.ListCriteriaField = value;
                    this.RaisePropertyChanged("ListCriteria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyNLuxHolder.HolderIdentity> IdentityCriteria
        {
            get
            {
                return this.IdentityCriteriaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.IdentityCriteriaField, value) != true))
                {
                    this.IdentityCriteriaField = value;
                    this.RaisePropertyChanged("IdentityCriteria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyNLuxHolder.OrganizationIdentity> CustomerAdministratorCriteria
        {
            get
            {
                return this.CustomerAdministratorCriteriaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CustomerAdministratorCriteriaField, value) != true))
                {
                    this.CustomerAdministratorCriteriaField = value;
                    this.RaisePropertyChanged("CustomerAdministratorCriteria");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CriteriaOptions", Namespace="http://www.tieto.com/cmw/tcm/holder")]
    public partial class CriteriaOptions : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private System.Nullable<bool> ShowActiveField;
        
        private System.Nullable<bool> ShowInactiveField;
        
        private System.Nullable<long> BrowseFromField;
        
        private System.Nullable<long> BrowseToField;
        
        private string SortFieldField;
        
        private string SortOrderField;
        
        private System.Nullable<bool> CaseSensitiveField;
        
        private string ExtPosReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<bool> ShowActive
        {
            get
            {
                return this.ShowActiveField;
            }
            set
            {
                if ((this.ShowActiveField.Equals(value) != true))
                {
                    this.ShowActiveField = value;
                    this.RaisePropertyChanged("ShowActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<bool> ShowInactive
        {
            get
            {
                return this.ShowInactiveField;
            }
            set
            {
                if ((this.ShowInactiveField.Equals(value) != true))
                {
                    this.ShowInactiveField = value;
                    this.RaisePropertyChanged("ShowInactive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Nullable<long> BrowseFrom
        {
            get
            {
                return this.BrowseFromField;
            }
            set
            {
                if ((this.BrowseFromField.Equals(value) != true))
                {
                    this.BrowseFromField = value;
                    this.RaisePropertyChanged("BrowseFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Nullable<long> BrowseTo
        {
            get
            {
                return this.BrowseToField;
            }
            set
            {
                if ((this.BrowseToField.Equals(value) != true))
                {
                    this.BrowseToField = value;
                    this.RaisePropertyChanged("BrowseTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SortField
        {
            get
            {
                return this.SortFieldField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SortFieldField, value) != true))
                {
                    this.SortFieldField = value;
                    this.RaisePropertyChanged("SortField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SortOrder
        {
            get
            {
                return this.SortOrderField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SortOrderField, value) != true))
                {
                    this.SortOrderField = value;
                    this.RaisePropertyChanged("SortOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public System.Nullable<bool> CaseSensitive
        {
            get
            {
                return this.CaseSensitiveField;
            }
            set
            {
                if ((this.CaseSensitiveField.Equals(value) != true))
                {
                    this.CaseSensitiveField = value;
                    this.RaisePropertyChanged("CaseSensitive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ExtPosReference
        {
            get
            {
                return this.ExtPosReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtPosReferenceField, value) != true))
                {
                    this.ExtPosReferenceField = value;
                    this.RaisePropertyChanged("ExtPosReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneralCriterion", Namespace="http://www.tieto.com/cmw/tcm/holder")]
    public partial class GeneralCriterion : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string SearchConcatenatorIdField;
        
        private string SearchFieldIdField;
        
        private string SearchOperatorIdField;
        
        private string SearchValueField;
        
        private string ExtPosReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SearchConcatenatorId
        {
            get
            {
                return this.SearchConcatenatorIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SearchConcatenatorIdField, value) != true))
                {
                    this.SearchConcatenatorIdField = value;
                    this.RaisePropertyChanged("SearchConcatenatorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SearchFieldId
        {
            get
            {
                return this.SearchFieldIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SearchFieldIdField, value) != true))
                {
                    this.SearchFieldIdField = value;
                    this.RaisePropertyChanged("SearchFieldId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SearchOperatorId
        {
            get
            {
                return this.SearchOperatorIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SearchOperatorIdField, value) != true))
                {
                    this.SearchOperatorIdField = value;
                    this.RaisePropertyChanged("SearchOperatorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SearchValue
        {
            get
            {
                return this.SearchValueField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SearchValueField, value) != true))
                {
                    this.SearchValueField = value;
                    this.RaisePropertyChanged("SearchValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ExtPosReference
        {
            get
            {
                return this.ExtPosReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtPosReferenceField, value) != true))
                {
                    this.ExtPosReferenceField = value;
                    this.RaisePropertyChanged("ExtPosReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SimpleCriterion", Namespace="http://www.tieto.com/cmw/tcm/holder")]
    public partial class SimpleCriterion : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string SearchFieldIdField;
        
        private string SearchValueField;
        
        private string ExtPosReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SearchFieldId
        {
            get
            {
                return this.SearchFieldIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SearchFieldIdField, value) != true))
                {
                    this.SearchFieldIdField = value;
                    this.RaisePropertyChanged("SearchFieldId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SearchValue
        {
            get
            {
                return this.SearchValueField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SearchValueField, value) != true))
                {
                    this.SearchValueField = value;
                    this.RaisePropertyChanged("SearchValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ExtPosReference
        {
            get
            {
                return this.ExtPosReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtPosReferenceField, value) != true))
                {
                    this.ExtPosReferenceField = value;
                    this.RaisePropertyChanged("ExtPosReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HolderRepositoryOutput", Namespace="http://www.tieto.com/cmw/tcm/holder")]
    public partial class HolderRepositoryOutput : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private bool SuccessField;
        
        private TCM.Web.Business.ProxyNLuxHolder.HolderRepository HolderRepositoryField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyNLuxHolder.Error> ErrorListField;
        
        private TCM.Web.Business.ProxyNLuxHolder.Context OutputContextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                if ((this.SuccessField.Equals(value) != true))
                {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public TCM.Web.Business.ProxyNLuxHolder.HolderRepository HolderRepository
        {
            get
            {
                return this.HolderRepositoryField;
            }
            set
            {
                if ((object.ReferenceEquals(this.HolderRepositoryField, value) != true))
                {
                    this.HolderRepositoryField = value;
                    this.RaisePropertyChanged("HolderRepository");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyNLuxHolder.Error> ErrorList
        {
            get
            {
                return this.ErrorListField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorListField, value) != true))
                {
                    this.ErrorListField = value;
                    this.RaisePropertyChanged("ErrorList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public TCM.Web.Business.ProxyNLuxHolder.Context OutputContext
        {
            get
            {
                return this.OutputContextField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OutputContextField, value) != true))
                {
                    this.OutputContextField = value;
                    this.RaisePropertyChanged("OutputContext");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.tieto.com/cmw/tcm/holder", ConfigurationName="TCM.Web.Business.ProxyNLuxHolder.IWSHolder")]
    public interface IWSHolder
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tieto.com/cmw/tcm/holder/IWSHolder/BeneficialOwnerSave", ReplyAction="http://www.tieto.com/cmw/tcm/holder/IWSHolder/BeneficialOwnerSaveResponse")]
        System.Threading.Tasks.Task<TCM.Web.Business.ProxyNLuxHolder.HolderOutput> BeneficialOwnerSaveAsync(TCM.Web.Business.ProxyNLuxHolder.HolderInput inputDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tieto.com/cmw/tcm/holder/IWSHolder/Find", ReplyAction="http://www.tieto.com/cmw/tcm/holder/IWSHolder/FindResponse")]
        System.Threading.Tasks.Task<TCM.Web.Business.ProxyNLuxHolder.HolderRepositoryOutput> FindAsync(TCM.Web.Business.ProxyNLuxHolder.HolderRepositoryInput inputDTO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public interface IWSHolderChannel : TCM.Web.Business.ProxyNLuxHolder.IWSHolder, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public partial class WSHolderClient : System.ServiceModel.ClientBase<TCM.Web.Business.ProxyNLuxHolder.IWSHolder>, TCM.Web.Business.ProxyNLuxHolder.IWSHolder
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSHolderClient() : 
                base(WSHolderClient.GetDefaultBinding(), WSHolderClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IWSHolder.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSHolderClient(EndpointConfiguration endpointConfiguration) : 
                base(WSHolderClient.GetBindingForEndpoint(endpointConfiguration), WSHolderClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSHolderClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSHolderClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSHolderClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSHolderClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSHolderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<TCM.Web.Business.ProxyNLuxHolder.HolderOutput> BeneficialOwnerSaveAsync(TCM.Web.Business.ProxyNLuxHolder.HolderInput inputDTO)
        {
            return base.Channel.BeneficialOwnerSaveAsync(inputDTO);
        }
        
        public System.Threading.Tasks.Task<TCM.Web.Business.ProxyNLuxHolder.HolderRepositoryOutput> FindAsync(TCM.Web.Business.ProxyNLuxHolder.HolderRepositoryInput inputDTO)
        {
            return base.Channel.FindAsync(inputDTO);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWSHolder))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWSHolder))
            {
                return new System.ServiceModel.EndpointAddress("http://tcmnordeaapp.bise.financialsolutions.se:8099/WSHolder.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WSHolderClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IWSHolder);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WSHolderClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IWSHolder);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IWSHolder,
        }
    }
}
