//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCM.Web.Business.ProxyLightCustomer
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountRepositoryInput", Namespace="http://www.tieto.com/cmw/tcm/customerservice")]
    public partial class AccountRepositoryInput : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private TCM.Web.Business.ProxyLightCustomer.AccountRepository AccountRepositoryField;
        
        private TCM.Web.Business.ProxyLightCustomer.Context InputContextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TCM.Web.Business.ProxyLightCustomer.AccountRepository AccountRepository
        {
            get
            {
                return this.AccountRepositoryField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AccountRepositoryField, value) != true))
                {
                    this.AccountRepositoryField = value;
                    this.RaisePropertyChanged("AccountRepository");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TCM.Web.Business.ProxyLightCustomer.Context InputContext
        {
            get
            {
                return this.InputContextField;
            }
            set
            {
                if ((object.ReferenceEquals(this.InputContextField, value) != true))
                {
                    this.InputContextField = value;
                    this.RaisePropertyChanged("InputContext");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountRepository", Namespace="http://www.tieto.com/cmw/tcm/customerservice")]
    public partial class AccountRepository : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private TCM.Web.Business.ProxyLightCustomer.CriteriaOptions OptionsField;
        
        private string CriteriaTypeField;
        
        private System.Nullable<long> TotalRecordsField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyLightCustomer.Account> AccountListField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyLightCustomer.GeneralCriterion> SearchCriteriaField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyLightCustomer.SimpleCriterion> ListCriteriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TCM.Web.Business.ProxyLightCustomer.CriteriaOptions Options
        {
            get
            {
                return this.OptionsField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OptionsField, value) != true))
                {
                    this.OptionsField = value;
                    this.RaisePropertyChanged("Options");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CriteriaType
        {
            get
            {
                return this.CriteriaTypeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CriteriaTypeField, value) != true))
                {
                    this.CriteriaTypeField = value;
                    this.RaisePropertyChanged("CriteriaType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Nullable<long> TotalRecords
        {
            get
            {
                return this.TotalRecordsField;
            }
            set
            {
                if ((this.TotalRecordsField.Equals(value) != true))
                {
                    this.TotalRecordsField = value;
                    this.RaisePropertyChanged("TotalRecords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyLightCustomer.Account> AccountList
        {
            get
            {
                return this.AccountListField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AccountListField, value) != true))
                {
                    this.AccountListField = value;
                    this.RaisePropertyChanged("AccountList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyLightCustomer.GeneralCriterion> SearchCriteria
        {
            get
            {
                return this.SearchCriteriaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SearchCriteriaField, value) != true))
                {
                    this.SearchCriteriaField = value;
                    this.RaisePropertyChanged("SearchCriteria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyLightCustomer.SimpleCriterion> ListCriteria
        {
            get
            {
                return this.ListCriteriaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ListCriteriaField, value) != true))
                {
                    this.ListCriteriaField = value;
                    this.RaisePropertyChanged("ListCriteria");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Context", Namespace="http://www.tieto.com/cmw/tcm/")]
    public partial class Context : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string ClientRowVersionField;
        
        private System.Nullable<System.DateTime> CreatedDateField;
        
        private string ExtChannelIdField;
        
        private string ExtIdField;
        
        private string ExtPosReferenceField;
        
        private string ExtUserField;
        
        private string LanguageIdField;
        
        private System.Nullable<System.DateTime> RegDateField;
        
        private string RegInterfaceField;
        
        private System.Nullable<long> RegTokenField;
        
        private string RegUserField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ClientRowVersion
        {
            get
            {
                return this.ClientRowVersionField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ClientRowVersionField, value) != true))
                {
                    this.ClientRowVersionField = value;
                    this.RaisePropertyChanged("ClientRowVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<System.DateTime> CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                if ((this.CreatedDateField.Equals(value) != true))
                {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExtChannelId
        {
            get
            {
                return this.ExtChannelIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtChannelIdField, value) != true))
                {
                    this.ExtChannelIdField = value;
                    this.RaisePropertyChanged("ExtChannelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExtId
        {
            get
            {
                return this.ExtIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtIdField, value) != true))
                {
                    this.ExtIdField = value;
                    this.RaisePropertyChanged("ExtId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExtPosReference
        {
            get
            {
                return this.ExtPosReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtPosReferenceField, value) != true))
                {
                    this.ExtPosReferenceField = value;
                    this.RaisePropertyChanged("ExtPosReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExtUser
        {
            get
            {
                return this.ExtUserField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtUserField, value) != true))
                {
                    this.ExtUserField = value;
                    this.RaisePropertyChanged("ExtUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LanguageId
        {
            get
            {
                return this.LanguageIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LanguageIdField, value) != true))
                {
                    this.LanguageIdField = value;
                    this.RaisePropertyChanged("LanguageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<System.DateTime> RegDate
        {
            get
            {
                return this.RegDateField;
            }
            set
            {
                if ((this.RegDateField.Equals(value) != true))
                {
                    this.RegDateField = value;
                    this.RaisePropertyChanged("RegDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RegInterface
        {
            get
            {
                return this.RegInterfaceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.RegInterfaceField, value) != true))
                {
                    this.RegInterfaceField = value;
                    this.RaisePropertyChanged("RegInterface");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<long> RegToken
        {
            get
            {
                return this.RegTokenField;
            }
            set
            {
                if ((this.RegTokenField.Equals(value) != true))
                {
                    this.RegTokenField = value;
                    this.RaisePropertyChanged("RegToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RegUser
        {
            get
            {
                return this.RegUserField;
            }
            set
            {
                if ((object.ReferenceEquals(this.RegUserField, value) != true))
                {
                    this.RegUserField = value;
                    this.RaisePropertyChanged("RegUser");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CriteriaOptions", Namespace="http://www.tieto.com/cmw/tcm/customerservice")]
    public partial class CriteriaOptions : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private System.Nullable<bool> ShowActiveField;
        
        private System.Nullable<bool> ShowInactiveField;
        
        private System.Nullable<long> BrowseFromField;
        
        private System.Nullable<long> BrowseToField;
        
        private string SortFieldField;
        
        private string SortOrderField;
        
        private System.Nullable<bool> CaseSensitiveField;
        
        private string ExtPosReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<bool> ShowActive
        {
            get
            {
                return this.ShowActiveField;
            }
            set
            {
                if ((this.ShowActiveField.Equals(value) != true))
                {
                    this.ShowActiveField = value;
                    this.RaisePropertyChanged("ShowActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<bool> ShowInactive
        {
            get
            {
                return this.ShowInactiveField;
            }
            set
            {
                if ((this.ShowInactiveField.Equals(value) != true))
                {
                    this.ShowInactiveField = value;
                    this.RaisePropertyChanged("ShowInactive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Nullable<long> BrowseFrom
        {
            get
            {
                return this.BrowseFromField;
            }
            set
            {
                if ((this.BrowseFromField.Equals(value) != true))
                {
                    this.BrowseFromField = value;
                    this.RaisePropertyChanged("BrowseFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Nullable<long> BrowseTo
        {
            get
            {
                return this.BrowseToField;
            }
            set
            {
                if ((this.BrowseToField.Equals(value) != true))
                {
                    this.BrowseToField = value;
                    this.RaisePropertyChanged("BrowseTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SortField
        {
            get
            {
                return this.SortFieldField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SortFieldField, value) != true))
                {
                    this.SortFieldField = value;
                    this.RaisePropertyChanged("SortField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SortOrder
        {
            get
            {
                return this.SortOrderField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SortOrderField, value) != true))
                {
                    this.SortOrderField = value;
                    this.RaisePropertyChanged("SortOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public System.Nullable<bool> CaseSensitive
        {
            get
            {
                return this.CaseSensitiveField;
            }
            set
            {
                if ((this.CaseSensitiveField.Equals(value) != true))
                {
                    this.CaseSensitiveField = value;
                    this.RaisePropertyChanged("CaseSensitive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ExtPosReference
        {
            get
            {
                return this.ExtPosReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtPosReferenceField, value) != true))
                {
                    this.ExtPosReferenceField = value;
                    this.RaisePropertyChanged("ExtPosReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://www.tieto.com/cmw/tcm/customerservice")]
    public partial class Account : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private System.Nullable<long> AccountIdField;
        
        private string AccountNumberField;
        
        private string AccountNumberTypeField;
        
        private string AccountTypeCodeField;
        
        private string BaseCurrencyField;
        
        private string LabelField;
        
        private string CustomerIdentificationNumberField;
        
        private System.Nullable<System.DateTime> EndDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<long> AccountId
        {
            get
            {
                return this.AccountIdField;
            }
            set
            {
                if ((this.AccountIdField.Equals(value) != true))
                {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AccountNumber
        {
            get
            {
                return this.AccountNumberField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true))
                {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AccountNumberType
        {
            get
            {
                return this.AccountNumberTypeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AccountNumberTypeField, value) != true))
                {
                    this.AccountNumberTypeField = value;
                    this.RaisePropertyChanged("AccountNumberType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AccountTypeCode
        {
            get
            {
                return this.AccountTypeCodeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AccountTypeCodeField, value) != true))
                {
                    this.AccountTypeCodeField = value;
                    this.RaisePropertyChanged("AccountTypeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BaseCurrency
        {
            get
            {
                return this.BaseCurrencyField;
            }
            set
            {
                if ((object.ReferenceEquals(this.BaseCurrencyField, value) != true))
                {
                    this.BaseCurrencyField = value;
                    this.RaisePropertyChanged("BaseCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Label
        {
            get
            {
                return this.LabelField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LabelField, value) != true))
                {
                    this.LabelField = value;
                    this.RaisePropertyChanged("Label");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CustomerIdentificationNumber
        {
            get
            {
                return this.CustomerIdentificationNumberField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CustomerIdentificationNumberField, value) != true))
                {
                    this.CustomerIdentificationNumberField = value;
                    this.RaisePropertyChanged("CustomerIdentificationNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public System.Nullable<System.DateTime> EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                if ((this.EndDateField.Equals(value) != true))
                {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneralCriterion", Namespace="http://www.tieto.com/cmw/tcm/customerservice")]
    public partial class GeneralCriterion : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string SearchConcatenatorIdField;
        
        private string SearchFieldIdField;
        
        private string SearchOperatorIdField;
        
        private string SearchValueField;
        
        private string ExtPosReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SearchConcatenatorId
        {
            get
            {
                return this.SearchConcatenatorIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SearchConcatenatorIdField, value) != true))
                {
                    this.SearchConcatenatorIdField = value;
                    this.RaisePropertyChanged("SearchConcatenatorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SearchFieldId
        {
            get
            {
                return this.SearchFieldIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SearchFieldIdField, value) != true))
                {
                    this.SearchFieldIdField = value;
                    this.RaisePropertyChanged("SearchFieldId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SearchOperatorId
        {
            get
            {
                return this.SearchOperatorIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SearchOperatorIdField, value) != true))
                {
                    this.SearchOperatorIdField = value;
                    this.RaisePropertyChanged("SearchOperatorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SearchValue
        {
            get
            {
                return this.SearchValueField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SearchValueField, value) != true))
                {
                    this.SearchValueField = value;
                    this.RaisePropertyChanged("SearchValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ExtPosReference
        {
            get
            {
                return this.ExtPosReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtPosReferenceField, value) != true))
                {
                    this.ExtPosReferenceField = value;
                    this.RaisePropertyChanged("ExtPosReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SimpleCriterion", Namespace="http://www.tieto.com/cmw/tcm/customerservice")]
    public partial class SimpleCriterion : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string SearchFieldIdField;
        
        private string SearchValueField;
        
        private string ExtPosReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SearchFieldId
        {
            get
            {
                return this.SearchFieldIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SearchFieldIdField, value) != true))
                {
                    this.SearchFieldIdField = value;
                    this.RaisePropertyChanged("SearchFieldId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SearchValue
        {
            get
            {
                return this.SearchValueField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SearchValueField, value) != true))
                {
                    this.SearchValueField = value;
                    this.RaisePropertyChanged("SearchValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ExtPosReference
        {
            get
            {
                return this.ExtPosReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtPosReferenceField, value) != true))
                {
                    this.ExtPosReferenceField = value;
                    this.RaisePropertyChanged("ExtPosReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountRepositoryOutput", Namespace="http://www.tieto.com/cmw/tcm/customerservice")]
    public partial class AccountRepositoryOutput : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private bool SuccessField;
        
        private TCM.Web.Business.ProxyLightCustomer.AccountRepository AccountRepositoryField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyLightCustomer.Error> ErrorListField;
        
        private TCM.Web.Business.ProxyLightCustomer.Context OutputContextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                if ((this.SuccessField.Equals(value) != true))
                {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public TCM.Web.Business.ProxyLightCustomer.AccountRepository AccountRepository
        {
            get
            {
                return this.AccountRepositoryField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AccountRepositoryField, value) != true))
                {
                    this.AccountRepositoryField = value;
                    this.RaisePropertyChanged("AccountRepository");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyLightCustomer.Error> ErrorList
        {
            get
            {
                return this.ErrorListField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorListField, value) != true))
                {
                    this.ErrorListField = value;
                    this.RaisePropertyChanged("ErrorList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public TCM.Web.Business.ProxyLightCustomer.Context OutputContext
        {
            get
            {
                return this.OutputContextField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OutputContextField, value) != true))
                {
                    this.OutputContextField = value;
                    this.RaisePropertyChanged("OutputContext");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://www.tieto.com/cmw/tcm/")]
    public partial class Error : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string ErrorCodeField;
        
        private string ErrorMessageField;
        
        private string ExtErrorPosReferenceField;
        
        private string SystemErrorMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true))
                {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true))
                {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtErrorPosReference
        {
            get
            {
                return this.ExtErrorPosReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtErrorPosReferenceField, value) != true))
                {
                    this.ExtErrorPosReferenceField = value;
                    this.RaisePropertyChanged("ExtErrorPosReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SystemErrorMessage
        {
            get
            {
                return this.SystemErrorMessageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SystemErrorMessageField, value) != true))
                {
                    this.SystemErrorMessageField = value;
                    this.RaisePropertyChanged("SystemErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerRepositoryInput", Namespace="http://www.tieto.com/cmw/tcm/customerservice")]
    public partial class CustomerRepositoryInput : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private TCM.Web.Business.ProxyLightCustomer.CustomerRepository CustomerRepositoryField;
        
        private TCM.Web.Business.ProxyLightCustomer.Context InputContextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TCM.Web.Business.ProxyLightCustomer.CustomerRepository CustomerRepository
        {
            get
            {
                return this.CustomerRepositoryField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CustomerRepositoryField, value) != true))
                {
                    this.CustomerRepositoryField = value;
                    this.RaisePropertyChanged("CustomerRepository");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TCM.Web.Business.ProxyLightCustomer.Context InputContext
        {
            get
            {
                return this.InputContextField;
            }
            set
            {
                if ((object.ReferenceEquals(this.InputContextField, value) != true))
                {
                    this.InputContextField = value;
                    this.RaisePropertyChanged("InputContext");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerRepository", Namespace="http://www.tieto.com/cmw/tcm/customerservice")]
    public partial class CustomerRepository : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private TCM.Web.Business.ProxyLightCustomer.CriteriaOptions OptionsField;
        
        private string CriteriaTypeField;
        
        private System.Nullable<long> TotalRecordsField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyLightCustomer.Customer> CustomerListField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyLightCustomer.GeneralCriterion> SearchCriteriaField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyLightCustomer.SimpleCriterion> ListCriteriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TCM.Web.Business.ProxyLightCustomer.CriteriaOptions Options
        {
            get
            {
                return this.OptionsField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OptionsField, value) != true))
                {
                    this.OptionsField = value;
                    this.RaisePropertyChanged("Options");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CriteriaType
        {
            get
            {
                return this.CriteriaTypeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CriteriaTypeField, value) != true))
                {
                    this.CriteriaTypeField = value;
                    this.RaisePropertyChanged("CriteriaType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Nullable<long> TotalRecords
        {
            get
            {
                return this.TotalRecordsField;
            }
            set
            {
                if ((this.TotalRecordsField.Equals(value) != true))
                {
                    this.TotalRecordsField = value;
                    this.RaisePropertyChanged("TotalRecords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyLightCustomer.Customer> CustomerList
        {
            get
            {
                return this.CustomerListField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CustomerListField, value) != true))
                {
                    this.CustomerListField = value;
                    this.RaisePropertyChanged("CustomerList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyLightCustomer.GeneralCriterion> SearchCriteria
        {
            get
            {
                return this.SearchCriteriaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SearchCriteriaField, value) != true))
                {
                    this.SearchCriteriaField = value;
                    this.RaisePropertyChanged("SearchCriteria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyLightCustomer.SimpleCriterion> ListCriteria
        {
            get
            {
                return this.ListCriteriaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ListCriteriaField, value) != true))
                {
                    this.ListCriteriaField = value;
                    this.RaisePropertyChanged("ListCriteria");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://www.tieto.com/cmw/tcm/customerservice")]
    public partial class Customer : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private System.Nullable<int> IDField;
        
        private string TypeField;
        
        private string ExternalIdField;
        
        private string IdentificationNumberField;
        
        private System.Nullable<System.DateTime> BirthDateField;
        
        private System.Nullable<System.DateTime> DeathDateField;
        
        private string AddressTypeField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private string OrganisationNameField;
        
        private string Address1Field;
        
        private string Address2Field;
        
        private string PostBoxField;
        
        private string PostCodeField;
        
        private string CityField;
        
        private string StateField;
        
        private string CountryField;
        
        private string SectorCodeField;
        
        private string TaxCountryField;
        
        private string IBANField;
        
        private string BBANField;
        
        private string BICField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyLightCustomer.Contact> ContactListField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyLightCustomer.Role> RoleListField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyLightCustomer.BeneficialOwner> BeneficialOwnerListField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<int> ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                if ((this.IDField.Equals(value) != true))
                {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TypeField, value) != true))
                {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ExternalId
        {
            get
            {
                return this.ExternalIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExternalIdField, value) != true))
                {
                    this.ExternalIdField = value;
                    this.RaisePropertyChanged("ExternalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string IdentificationNumber
        {
            get
            {
                return this.IdentificationNumberField;
            }
            set
            {
                if ((object.ReferenceEquals(this.IdentificationNumberField, value) != true))
                {
                    this.IdentificationNumberField = value;
                    this.RaisePropertyChanged("IdentificationNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public System.Nullable<System.DateTime> BirthDate
        {
            get
            {
                return this.BirthDateField;
            }
            set
            {
                if ((this.BirthDateField.Equals(value) != true))
                {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public System.Nullable<System.DateTime> DeathDate
        {
            get
            {
                return this.DeathDateField;
            }
            set
            {
                if ((this.DeathDateField.Equals(value) != true))
                {
                    this.DeathDateField = value;
                    this.RaisePropertyChanged("DeathDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string AddressType
        {
            get
            {
                return this.AddressTypeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AddressTypeField, value) != true))
                {
                    this.AddressTypeField = value;
                    this.RaisePropertyChanged("AddressType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true))
                {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LastNameField, value) != true))
                {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string OrganisationName
        {
            get
            {
                return this.OrganisationNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OrganisationNameField, value) != true))
                {
                    this.OrganisationNameField = value;
                    this.RaisePropertyChanged("OrganisationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Address1
        {
            get
            {
                return this.Address1Field;
            }
            set
            {
                if ((object.ReferenceEquals(this.Address1Field, value) != true))
                {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Address2
        {
            get
            {
                return this.Address2Field;
            }
            set
            {
                if ((object.ReferenceEquals(this.Address2Field, value) != true))
                {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string PostBox
        {
            get
            {
                return this.PostBoxField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PostBoxField, value) != true))
                {
                    this.PostBoxField = value;
                    this.RaisePropertyChanged("PostBox");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string PostCode
        {
            get
            {
                return this.PostCodeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PostCodeField, value) != true))
                {
                    this.PostCodeField = value;
                    this.RaisePropertyChanged("PostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CityField, value) != true))
                {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                if ((object.ReferenceEquals(this.StateField, value) != true))
                {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CountryField, value) != true))
                {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string SectorCode
        {
            get
            {
                return this.SectorCodeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SectorCodeField, value) != true))
                {
                    this.SectorCodeField = value;
                    this.RaisePropertyChanged("SectorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string TaxCountry
        {
            get
            {
                return this.TaxCountryField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TaxCountryField, value) != true))
                {
                    this.TaxCountryField = value;
                    this.RaisePropertyChanged("TaxCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string IBAN
        {
            get
            {
                return this.IBANField;
            }
            set
            {
                if ((object.ReferenceEquals(this.IBANField, value) != true))
                {
                    this.IBANField = value;
                    this.RaisePropertyChanged("IBAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string BBAN
        {
            get
            {
                return this.BBANField;
            }
            set
            {
                if ((object.ReferenceEquals(this.BBANField, value) != true))
                {
                    this.BBANField = value;
                    this.RaisePropertyChanged("BBAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string BIC
        {
            get
            {
                return this.BICField;
            }
            set
            {
                if ((object.ReferenceEquals(this.BICField, value) != true))
                {
                    this.BICField = value;
                    this.RaisePropertyChanged("BIC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyLightCustomer.Contact> ContactList
        {
            get
            {
                return this.ContactListField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ContactListField, value) != true))
                {
                    this.ContactListField = value;
                    this.RaisePropertyChanged("ContactList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyLightCustomer.Role> RoleList
        {
            get
            {
                return this.RoleListField;
            }
            set
            {
                if ((object.ReferenceEquals(this.RoleListField, value) != true))
                {
                    this.RoleListField = value;
                    this.RaisePropertyChanged("RoleList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyLightCustomer.BeneficialOwner> BeneficialOwnerList
        {
            get
            {
                return this.BeneficialOwnerListField;
            }
            set
            {
                if ((object.ReferenceEquals(this.BeneficialOwnerListField, value) != true))
                {
                    this.BeneficialOwnerListField = value;
                    this.RaisePropertyChanged("BeneficialOwnerList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contact", Namespace="http://www.tieto.com/cmw/tcm/customerservice")]
    public partial class Contact : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string TypeField;
        
        private string ContactNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TypeField, value) != true))
                {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ContactNumber
        {
            get
            {
                return this.ContactNumberField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ContactNumberField, value) != true))
                {
                    this.ContactNumberField = value;
                    this.RaisePropertyChanged("ContactNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://www.tieto.com/cmw/tcm/customerservice")]
    public partial class Role : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string TypeField;
        
        private string CustomerIdentificationNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TypeField, value) != true))
                {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CustomerIdentificationNumber
        {
            get
            {
                return this.CustomerIdentificationNumberField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CustomerIdentificationNumberField, value) != true))
                {
                    this.CustomerIdentificationNumberField = value;
                    this.RaisePropertyChanged("CustomerIdentificationNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BeneficialOwner", Namespace="http://www.tieto.com/cmw/tcm/customerservice")]
    public partial class BeneficialOwner : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string TypeField;
        
        private string CustomerIdentificationNumberField;
        
        private System.Nullable<decimal> PercentageRateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TypeField, value) != true))
                {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CustomerIdentificationNumber
        {
            get
            {
                return this.CustomerIdentificationNumberField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CustomerIdentificationNumberField, value) != true))
                {
                    this.CustomerIdentificationNumberField = value;
                    this.RaisePropertyChanged("CustomerIdentificationNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Nullable<decimal> PercentageRate
        {
            get
            {
                return this.PercentageRateField;
            }
            set
            {
                if ((this.PercentageRateField.Equals(value) != true))
                {
                    this.PercentageRateField = value;
                    this.RaisePropertyChanged("PercentageRate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerRepositoryOutput", Namespace="http://www.tieto.com/cmw/tcm/customerservice")]
    public partial class CustomerRepositoryOutput : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private bool SuccessField;
        
        private TCM.Web.Business.ProxyLightCustomer.CustomerRepository CustomerRepositoryField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyLightCustomer.Error> ErrorListField;
        
        private TCM.Web.Business.ProxyLightCustomer.Context OutputContextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                if ((this.SuccessField.Equals(value) != true))
                {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public TCM.Web.Business.ProxyLightCustomer.CustomerRepository CustomerRepository
        {
            get
            {
                return this.CustomerRepositoryField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CustomerRepositoryField, value) != true))
                {
                    this.CustomerRepositoryField = value;
                    this.RaisePropertyChanged("CustomerRepository");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyLightCustomer.Error> ErrorList
        {
            get
            {
                return this.ErrorListField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorListField, value) != true))
                {
                    this.ErrorListField = value;
                    this.RaisePropertyChanged("ErrorList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public TCM.Web.Business.ProxyLightCustomer.Context OutputContext
        {
            get
            {
                return this.OutputContextField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OutputContextField, value) != true))
                {
                    this.OutputContextField = value;
                    this.RaisePropertyChanged("OutputContext");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.tieto.com/cmw/tcm/customerservice", ConfigurationName="TCM.Web.Business.ProxyLightCustomer.IWSCustomerService")]
    public interface IWSCustomerService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tieto.com/cmw/tcm/customerservice/IWSCustomerService/AccountFind", ReplyAction="http://www.tieto.com/cmw/tcm/customerservice/IWSCustomerService/AccountFindRespon" +
            "se")]
        System.Threading.Tasks.Task<TCM.Web.Business.ProxyLightCustomer.AccountRepositoryOutput> AccountFindAsync(TCM.Web.Business.ProxyLightCustomer.AccountRepositoryInput inputDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tieto.com/cmw/tcm/customerservice/IWSCustomerService/Find", ReplyAction="http://www.tieto.com/cmw/tcm/customerservice/IWSCustomerService/FindResponse")]
        System.Threading.Tasks.Task<TCM.Web.Business.ProxyLightCustomer.CustomerRepositoryOutput> FindAsync(TCM.Web.Business.ProxyLightCustomer.CustomerRepositoryInput inputDTO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public interface IWSCustomerServiceChannel : TCM.Web.Business.ProxyLightCustomer.IWSCustomerService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public partial class WSCustomerServiceClient : System.ServiceModel.ClientBase<TCM.Web.Business.ProxyLightCustomer.IWSCustomerService>, TCM.Web.Business.ProxyLightCustomer.IWSCustomerService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSCustomerServiceClient() : 
                base(WSCustomerServiceClient.GetDefaultBinding(), WSCustomerServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IWSCustomerService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSCustomerServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(WSCustomerServiceClient.GetBindingForEndpoint(endpointConfiguration), WSCustomerServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSCustomerServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSCustomerServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSCustomerServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSCustomerServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSCustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<TCM.Web.Business.ProxyLightCustomer.AccountRepositoryOutput> AccountFindAsync(TCM.Web.Business.ProxyLightCustomer.AccountRepositoryInput inputDTO)
        {
            return base.Channel.AccountFindAsync(inputDTO);
        }
        
        public System.Threading.Tasks.Task<TCM.Web.Business.ProxyLightCustomer.CustomerRepositoryOutput> FindAsync(TCM.Web.Business.ProxyLightCustomer.CustomerRepositoryInput inputDTO)
        {
            return base.Channel.FindAsync(inputDTO);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWSCustomerService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWSCustomerService))
            {
                return new System.ServiceModel.EndpointAddress("http://tcmbop2019.bise.financialsolutions.se:820/WSCustomerService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WSCustomerServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IWSCustomerService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WSCustomerServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IWSCustomerService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IWSCustomerService,
        }
    }
}
