//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCM.Web.Business.ProxyCash
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HolderCashBalanceRepositoryInput", Namespace="http://www.tieto.com/cmw/tcm/cash")]
    public partial class HolderCashBalanceRepositoryInput : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private TCM.Web.Business.ProxyCash.HolderCashBalanceRepository HolderCashBalanceRepositoryField;
        
        private TCM.Web.Business.ProxyCash.Context InputContextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TCM.Web.Business.ProxyCash.HolderCashBalanceRepository HolderCashBalanceRepository
        {
            get
            {
                return this.HolderCashBalanceRepositoryField;
            }
            set
            {
                if ((object.ReferenceEquals(this.HolderCashBalanceRepositoryField, value) != true))
                {
                    this.HolderCashBalanceRepositoryField = value;
                    this.RaisePropertyChanged("HolderCashBalanceRepository");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TCM.Web.Business.ProxyCash.Context InputContext
        {
            get
            {
                return this.InputContextField;
            }
            set
            {
                if ((object.ReferenceEquals(this.InputContextField, value) != true))
                {
                    this.InputContextField = value;
                    this.RaisePropertyChanged("InputContext");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HolderCashBalanceRepository", Namespace="http://www.tieto.com/cmw/tcm/cash")]
    public partial class HolderCashBalanceRepository : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private TCM.Web.Business.ProxyCash.CriteriaOptions OptionsField;
        
        private string CriteriaTypeField;
        
        private System.Nullable<long> TotalRecordsField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyCash.HolderCashBalance> HolderCashBalanceListField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyCash.GeneralCriterion> SearchCriteriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TCM.Web.Business.ProxyCash.CriteriaOptions Options
        {
            get
            {
                return this.OptionsField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OptionsField, value) != true))
                {
                    this.OptionsField = value;
                    this.RaisePropertyChanged("Options");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CriteriaType
        {
            get
            {
                return this.CriteriaTypeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CriteriaTypeField, value) != true))
                {
                    this.CriteriaTypeField = value;
                    this.RaisePropertyChanged("CriteriaType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Nullable<long> TotalRecords
        {
            get
            {
                return this.TotalRecordsField;
            }
            set
            {
                if ((this.TotalRecordsField.Equals(value) != true))
                {
                    this.TotalRecordsField = value;
                    this.RaisePropertyChanged("TotalRecords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyCash.HolderCashBalance> HolderCashBalanceList
        {
            get
            {
                return this.HolderCashBalanceListField;
            }
            set
            {
                if ((object.ReferenceEquals(this.HolderCashBalanceListField, value) != true))
                {
                    this.HolderCashBalanceListField = value;
                    this.RaisePropertyChanged("HolderCashBalanceList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyCash.GeneralCriterion> SearchCriteria
        {
            get
            {
                return this.SearchCriteriaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SearchCriteriaField, value) != true))
                {
                    this.SearchCriteriaField = value;
                    this.RaisePropertyChanged("SearchCriteria");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Context", Namespace="http://www.tieto.com/cmw/tcm/")]
    public partial class Context : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string ClientRowVersionField;
        
        private System.Nullable<System.DateTime> CreatedDateField;
        
        private string ExtChannelIdField;
        
        private string ExtIdField;
        
        private string ExtPosReferenceField;
        
        private string ExtUserField;
        
        private string LanguageIdField;
        
        private System.Nullable<System.DateTime> RegDateField;
        
        private string RegInterfaceField;
        
        private System.Nullable<long> RegTokenField;
        
        private string RegUserField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ClientRowVersion
        {
            get
            {
                return this.ClientRowVersionField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ClientRowVersionField, value) != true))
                {
                    this.ClientRowVersionField = value;
                    this.RaisePropertyChanged("ClientRowVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<System.DateTime> CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                if ((this.CreatedDateField.Equals(value) != true))
                {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExtChannelId
        {
            get
            {
                return this.ExtChannelIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtChannelIdField, value) != true))
                {
                    this.ExtChannelIdField = value;
                    this.RaisePropertyChanged("ExtChannelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExtId
        {
            get
            {
                return this.ExtIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtIdField, value) != true))
                {
                    this.ExtIdField = value;
                    this.RaisePropertyChanged("ExtId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExtPosReference
        {
            get
            {
                return this.ExtPosReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtPosReferenceField, value) != true))
                {
                    this.ExtPosReferenceField = value;
                    this.RaisePropertyChanged("ExtPosReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExtUser
        {
            get
            {
                return this.ExtUserField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtUserField, value) != true))
                {
                    this.ExtUserField = value;
                    this.RaisePropertyChanged("ExtUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LanguageId
        {
            get
            {
                return this.LanguageIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LanguageIdField, value) != true))
                {
                    this.LanguageIdField = value;
                    this.RaisePropertyChanged("LanguageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<System.DateTime> RegDate
        {
            get
            {
                return this.RegDateField;
            }
            set
            {
                if ((this.RegDateField.Equals(value) != true))
                {
                    this.RegDateField = value;
                    this.RaisePropertyChanged("RegDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RegInterface
        {
            get
            {
                return this.RegInterfaceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.RegInterfaceField, value) != true))
                {
                    this.RegInterfaceField = value;
                    this.RaisePropertyChanged("RegInterface");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<long> RegToken
        {
            get
            {
                return this.RegTokenField;
            }
            set
            {
                if ((this.RegTokenField.Equals(value) != true))
                {
                    this.RegTokenField = value;
                    this.RaisePropertyChanged("RegToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RegUser
        {
            get
            {
                return this.RegUserField;
            }
            set
            {
                if ((object.ReferenceEquals(this.RegUserField, value) != true))
                {
                    this.RegUserField = value;
                    this.RaisePropertyChanged("RegUser");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CriteriaOptions", Namespace="http://www.tieto.com/cmw/tcm/cash")]
    public partial class CriteriaOptions : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private System.Nullable<bool> ShowActiveField;
        
        private System.Nullable<bool> ShowInactiveField;
        
        private System.Nullable<long> BrowseFromField;
        
        private System.Nullable<long> BrowseToField;
        
        private string SortFieldField;
        
        private string SortOrderField;
        
        private System.Nullable<bool> CaseSensitiveField;
        
        private string ExtPosReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<bool> ShowActive
        {
            get
            {
                return this.ShowActiveField;
            }
            set
            {
                if ((this.ShowActiveField.Equals(value) != true))
                {
                    this.ShowActiveField = value;
                    this.RaisePropertyChanged("ShowActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<bool> ShowInactive
        {
            get
            {
                return this.ShowInactiveField;
            }
            set
            {
                if ((this.ShowInactiveField.Equals(value) != true))
                {
                    this.ShowInactiveField = value;
                    this.RaisePropertyChanged("ShowInactive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Nullable<long> BrowseFrom
        {
            get
            {
                return this.BrowseFromField;
            }
            set
            {
                if ((this.BrowseFromField.Equals(value) != true))
                {
                    this.BrowseFromField = value;
                    this.RaisePropertyChanged("BrowseFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Nullable<long> BrowseTo
        {
            get
            {
                return this.BrowseToField;
            }
            set
            {
                if ((this.BrowseToField.Equals(value) != true))
                {
                    this.BrowseToField = value;
                    this.RaisePropertyChanged("BrowseTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SortField
        {
            get
            {
                return this.SortFieldField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SortFieldField, value) != true))
                {
                    this.SortFieldField = value;
                    this.RaisePropertyChanged("SortField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SortOrder
        {
            get
            {
                return this.SortOrderField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SortOrderField, value) != true))
                {
                    this.SortOrderField = value;
                    this.RaisePropertyChanged("SortOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public System.Nullable<bool> CaseSensitive
        {
            get
            {
                return this.CaseSensitiveField;
            }
            set
            {
                if ((this.CaseSensitiveField.Equals(value) != true))
                {
                    this.CaseSensitiveField = value;
                    this.RaisePropertyChanged("CaseSensitive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ExtPosReference
        {
            get
            {
                return this.ExtPosReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtPosReferenceField, value) != true))
                {
                    this.ExtPosReferenceField = value;
                    this.RaisePropertyChanged("ExtPosReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HolderCashBalance", Namespace="http://www.tieto.com/cmw/tcm/cash")]
    public partial class HolderCashBalance : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string AccountIdField;
        
        private string AccountTypeIdField;
        
        private string ExternalAccountIdField;
        
        private System.Nullable<decimal> CashBalanceField;
        
        private string ExtPosReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AccountId
        {
            get
            {
                return this.AccountIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AccountIdField, value) != true))
                {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AccountTypeId
        {
            get
            {
                return this.AccountTypeIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AccountTypeIdField, value) != true))
                {
                    this.AccountTypeIdField = value;
                    this.RaisePropertyChanged("AccountTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExternalAccountId
        {
            get
            {
                return this.ExternalAccountIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExternalAccountIdField, value) != true))
                {
                    this.ExternalAccountIdField = value;
                    this.RaisePropertyChanged("ExternalAccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Nullable<decimal> CashBalance
        {
            get
            {
                return this.CashBalanceField;
            }
            set
            {
                if ((this.CashBalanceField.Equals(value) != true))
                {
                    this.CashBalanceField = value;
                    this.RaisePropertyChanged("CashBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ExtPosReference
        {
            get
            {
                return this.ExtPosReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtPosReferenceField, value) != true))
                {
                    this.ExtPosReferenceField = value;
                    this.RaisePropertyChanged("ExtPosReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneralCriterion", Namespace="http://www.tieto.com/cmw/tcm/cash")]
    public partial class GeneralCriterion : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string SearchConcatenatorIdField;
        
        private string SearchFieldIdField;
        
        private string SearchOperatorIdField;
        
        private string SearchValueField;
        
        private string ExtPosReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SearchConcatenatorId
        {
            get
            {
                return this.SearchConcatenatorIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SearchConcatenatorIdField, value) != true))
                {
                    this.SearchConcatenatorIdField = value;
                    this.RaisePropertyChanged("SearchConcatenatorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SearchFieldId
        {
            get
            {
                return this.SearchFieldIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SearchFieldIdField, value) != true))
                {
                    this.SearchFieldIdField = value;
                    this.RaisePropertyChanged("SearchFieldId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SearchOperatorId
        {
            get
            {
                return this.SearchOperatorIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SearchOperatorIdField, value) != true))
                {
                    this.SearchOperatorIdField = value;
                    this.RaisePropertyChanged("SearchOperatorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SearchValue
        {
            get
            {
                return this.SearchValueField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SearchValueField, value) != true))
                {
                    this.SearchValueField = value;
                    this.RaisePropertyChanged("SearchValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ExtPosReference
        {
            get
            {
                return this.ExtPosReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtPosReferenceField, value) != true))
                {
                    this.ExtPosReferenceField = value;
                    this.RaisePropertyChanged("ExtPosReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HolderCashBalanceRepositoryOutput", Namespace="http://www.tieto.com/cmw/tcm/cash")]
    public partial class HolderCashBalanceRepositoryOutput : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private bool SuccessField;
        
        private TCM.Web.Business.ProxyCash.HolderCashBalanceRepository HolderCashBalanceRepositoryField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyCash.Error> ErrorListField;
        
        private TCM.Web.Business.ProxyCash.Context OutputContextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                if ((this.SuccessField.Equals(value) != true))
                {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public TCM.Web.Business.ProxyCash.HolderCashBalanceRepository HolderCashBalanceRepository
        {
            get
            {
                return this.HolderCashBalanceRepositoryField;
            }
            set
            {
                if ((object.ReferenceEquals(this.HolderCashBalanceRepositoryField, value) != true))
                {
                    this.HolderCashBalanceRepositoryField = value;
                    this.RaisePropertyChanged("HolderCashBalanceRepository");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyCash.Error> ErrorList
        {
            get
            {
                return this.ErrorListField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorListField, value) != true))
                {
                    this.ErrorListField = value;
                    this.RaisePropertyChanged("ErrorList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public TCM.Web.Business.ProxyCash.Context OutputContext
        {
            get
            {
                return this.OutputContextField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OutputContextField, value) != true))
                {
                    this.OutputContextField = value;
                    this.RaisePropertyChanged("OutputContext");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://www.tieto.com/cmw/tcm/")]
    public partial class Error : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string ErrorCodeField;
        
        private string ErrorMessageField;
        
        private string ExtErrorPosReferenceField;
        
        private string SystemErrorMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true))
                {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true))
                {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtErrorPosReference
        {
            get
            {
                return this.ExtErrorPosReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtErrorPosReferenceField, value) != true))
                {
                    this.ExtErrorPosReferenceField = value;
                    this.RaisePropertyChanged("ExtErrorPosReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SystemErrorMessage
        {
            get
            {
                return this.SystemErrorMessageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SystemErrorMessageField, value) != true))
                {
                    this.SystemErrorMessageField = value;
                    this.RaisePropertyChanged("SystemErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HolderCashTransactionRepositoryInput", Namespace="http://www.tieto.com/cmw/tcm/cash")]
    public partial class HolderCashTransactionRepositoryInput : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private TCM.Web.Business.ProxyCash.HolderCashTransactionRepository HolderCashTransactionRepositoryField;
        
        private TCM.Web.Business.ProxyCash.Context InputContextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TCM.Web.Business.ProxyCash.HolderCashTransactionRepository HolderCashTransactionRepository
        {
            get
            {
                return this.HolderCashTransactionRepositoryField;
            }
            set
            {
                if ((object.ReferenceEquals(this.HolderCashTransactionRepositoryField, value) != true))
                {
                    this.HolderCashTransactionRepositoryField = value;
                    this.RaisePropertyChanged("HolderCashTransactionRepository");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TCM.Web.Business.ProxyCash.Context InputContext
        {
            get
            {
                return this.InputContextField;
            }
            set
            {
                if ((object.ReferenceEquals(this.InputContextField, value) != true))
                {
                    this.InputContextField = value;
                    this.RaisePropertyChanged("InputContext");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HolderCashTransactionRepository", Namespace="http://www.tieto.com/cmw/tcm/cash")]
    public partial class HolderCashTransactionRepository : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private TCM.Web.Business.ProxyCash.CriteriaOptions OptionsField;
        
        private string AccountIdField;
        
        private string ExternalAccountIdField;
        
        private string CriteriaTypeField;
        
        private System.Nullable<long> TotalRecordsField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyCash.HolderCashTransaction> HolderCashTransactionListField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TCM.Web.Business.ProxyCash.CriteriaOptions Options
        {
            get
            {
                return this.OptionsField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OptionsField, value) != true))
                {
                    this.OptionsField = value;
                    this.RaisePropertyChanged("Options");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AccountId
        {
            get
            {
                return this.AccountIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AccountIdField, value) != true))
                {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ExternalAccountId
        {
            get
            {
                return this.ExternalAccountIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExternalAccountIdField, value) != true))
                {
                    this.ExternalAccountIdField = value;
                    this.RaisePropertyChanged("ExternalAccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CriteriaType
        {
            get
            {
                return this.CriteriaTypeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CriteriaTypeField, value) != true))
                {
                    this.CriteriaTypeField = value;
                    this.RaisePropertyChanged("CriteriaType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public System.Nullable<long> TotalRecords
        {
            get
            {
                return this.TotalRecordsField;
            }
            set
            {
                if ((this.TotalRecordsField.Equals(value) != true))
                {
                    this.TotalRecordsField = value;
                    this.RaisePropertyChanged("TotalRecords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyCash.HolderCashTransaction> HolderCashTransactionList
        {
            get
            {
                return this.HolderCashTransactionListField;
            }
            set
            {
                if ((object.ReferenceEquals(this.HolderCashTransactionListField, value) != true))
                {
                    this.HolderCashTransactionListField = value;
                    this.RaisePropertyChanged("HolderCashTransactionList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HolderCashTransaction", Namespace="http://www.tieto.com/cmw/tcm/cash")]
    public partial class HolderCashTransaction : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private System.Nullable<long> TransactionIdField;
        
        private string AccountIdField;
        
        private string ExternalAccountIdField;
        
        private string TransactionTypeIdField;
        
        private System.Nullable<decimal> AmountField;
        
        private string CurrencyField;
        
        private System.Nullable<System.DateTime> BookingDateField;
        
        private string ExtPosReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<long> TransactionId
        {
            get
            {
                return this.TransactionIdField;
            }
            set
            {
                if ((this.TransactionIdField.Equals(value) != true))
                {
                    this.TransactionIdField = value;
                    this.RaisePropertyChanged("TransactionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AccountId
        {
            get
            {
                return this.AccountIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AccountIdField, value) != true))
                {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ExternalAccountId
        {
            get
            {
                return this.ExternalAccountIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExternalAccountIdField, value) != true))
                {
                    this.ExternalAccountIdField = value;
                    this.RaisePropertyChanged("ExternalAccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TransactionTypeId
        {
            get
            {
                return this.TransactionTypeIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TransactionTypeIdField, value) != true))
                {
                    this.TransactionTypeIdField = value;
                    this.RaisePropertyChanged("TransactionTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public System.Nullable<decimal> Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                if ((this.AmountField.Equals(value) != true))
                {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true))
                {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public System.Nullable<System.DateTime> BookingDate
        {
            get
            {
                return this.BookingDateField;
            }
            set
            {
                if ((this.BookingDateField.Equals(value) != true))
                {
                    this.BookingDateField = value;
                    this.RaisePropertyChanged("BookingDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ExtPosReference
        {
            get
            {
                return this.ExtPosReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtPosReferenceField, value) != true))
                {
                    this.ExtPosReferenceField = value;
                    this.RaisePropertyChanged("ExtPosReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HolderCashTransactionRepositoryOutput", Namespace="http://www.tieto.com/cmw/tcm/cash")]
    public partial class HolderCashTransactionRepositoryOutput : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private bool SuccessField;
        
        private TCM.Web.Business.ProxyCash.HolderCashTransactionRepository HolderCashTransactionRepositoryField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyCash.Error> ErrorListField;
        
        private TCM.Web.Business.ProxyCash.Context OutputContextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                if ((this.SuccessField.Equals(value) != true))
                {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public TCM.Web.Business.ProxyCash.HolderCashTransactionRepository HolderCashTransactionRepository
        {
            get
            {
                return this.HolderCashTransactionRepositoryField;
            }
            set
            {
                if ((object.ReferenceEquals(this.HolderCashTransactionRepositoryField, value) != true))
                {
                    this.HolderCashTransactionRepositoryField = value;
                    this.RaisePropertyChanged("HolderCashTransactionRepository");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyCash.Error> ErrorList
        {
            get
            {
                return this.ErrorListField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorListField, value) != true))
                {
                    this.ErrorListField = value;
                    this.RaisePropertyChanged("ErrorList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public TCM.Web.Business.ProxyCash.Context OutputContext
        {
            get
            {
                return this.OutputContextField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OutputContextField, value) != true))
                {
                    this.OutputContextField = value;
                    this.RaisePropertyChanged("OutputContext");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.tieto.com/cmw/tcm/cash", ConfigurationName="TCM.Web.Business.ProxyCash.IWSCash")]
    public interface IWSCash
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tieto.com/cmw/tcm/cash/IWSCash/HolderCashBalanceOverview", ReplyAction="http://www.tieto.com/cmw/tcm/cash/IWSCash/HolderCashBalanceOverviewResponse")]
        System.Threading.Tasks.Task<TCM.Web.Business.ProxyCash.HolderCashBalanceRepositoryOutput> HolderCashBalanceOverviewAsync(TCM.Web.Business.ProxyCash.HolderCashBalanceRepositoryInput inputDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tieto.com/cmw/tcm/cash/IWSCash/HolderCashTransactionOverview", ReplyAction="http://www.tieto.com/cmw/tcm/cash/IWSCash/HolderCashTransactionOverviewResponse")]
        System.Threading.Tasks.Task<TCM.Web.Business.ProxyCash.HolderCashTransactionRepositoryOutput> HolderCashTransactionOverviewAsync(TCM.Web.Business.ProxyCash.HolderCashTransactionRepositoryInput inputDTO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public interface IWSCashChannel : TCM.Web.Business.ProxyCash.IWSCash, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public partial class WSCashClient : System.ServiceModel.ClientBase<TCM.Web.Business.ProxyCash.IWSCash>, TCM.Web.Business.ProxyCash.IWSCash
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSCashClient() : 
                base(WSCashClient.GetDefaultBinding(), WSCashClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IWSCash.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSCashClient(EndpointConfiguration endpointConfiguration) : 
                base(WSCashClient.GetBindingForEndpoint(endpointConfiguration), WSCashClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSCashClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSCashClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSCashClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSCashClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSCashClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<TCM.Web.Business.ProxyCash.HolderCashBalanceRepositoryOutput> HolderCashBalanceOverviewAsync(TCM.Web.Business.ProxyCash.HolderCashBalanceRepositoryInput inputDTO)
        {
            return base.Channel.HolderCashBalanceOverviewAsync(inputDTO);
        }
        
        public System.Threading.Tasks.Task<TCM.Web.Business.ProxyCash.HolderCashTransactionRepositoryOutput> HolderCashTransactionOverviewAsync(TCM.Web.Business.ProxyCash.HolderCashTransactionRepositoryInput inputDTO)
        {
            return base.Channel.HolderCashTransactionOverviewAsync(inputDTO);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWSCash))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWSCash))
            {
                return new System.ServiceModel.EndpointAddress("http://tcmdg2012.bise.financialsolutions.se:800/WSCash.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WSCashClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IWSCash);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WSCashClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IWSCash);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IWSCash,
        }
    }
}
