//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCM.Web.Business.ProxyXFMOrganization
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrganizationRepositoryInput", Namespace="http://www.tieto.com/cmw/tcm/organization")]
    public partial class OrganizationRepositoryInput : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private TCM.Web.Business.ProxyXFMOrganization.OrganizationRepository OrganizationRepositoryField;
        
        private TCM.Web.Business.ProxyXFMOrganization.Context InputContextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TCM.Web.Business.ProxyXFMOrganization.OrganizationRepository OrganizationRepository
        {
            get
            {
                return this.OrganizationRepositoryField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OrganizationRepositoryField, value) != true))
                {
                    this.OrganizationRepositoryField = value;
                    this.RaisePropertyChanged("OrganizationRepository");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public TCM.Web.Business.ProxyXFMOrganization.Context InputContext
        {
            get
            {
                return this.InputContextField;
            }
            set
            {
                if ((object.ReferenceEquals(this.InputContextField, value) != true))
                {
                    this.InputContextField = value;
                    this.RaisePropertyChanged("InputContext");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrganizationRepository", Namespace="http://www.tieto.com/cmw/tcm/organization")]
    public partial class OrganizationRepository : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private TCM.Web.Business.ProxyXFMOrganization.CriteriaOptions OptionsField;
        
        private string CriteriaTypeField;
        
        private System.Nullable<long> TotalRecordsField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyXFMOrganization.OrganizationInfo> OrganizationListField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyXFMOrganization.GeneralCriterion> SearchCriteriaField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyXFMOrganization.SimpleCriterion> ListCriteriaField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyXFMOrganization.OrganizationIdentity> IdentityCriteriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TCM.Web.Business.ProxyXFMOrganization.CriteriaOptions Options
        {
            get
            {
                return this.OptionsField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OptionsField, value) != true))
                {
                    this.OptionsField = value;
                    this.RaisePropertyChanged("Options");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CriteriaType
        {
            get
            {
                return this.CriteriaTypeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CriteriaTypeField, value) != true))
                {
                    this.CriteriaTypeField = value;
                    this.RaisePropertyChanged("CriteriaType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Nullable<long> TotalRecords
        {
            get
            {
                return this.TotalRecordsField;
            }
            set
            {
                if ((this.TotalRecordsField.Equals(value) != true))
                {
                    this.TotalRecordsField = value;
                    this.RaisePropertyChanged("TotalRecords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyXFMOrganization.OrganizationInfo> OrganizationList
        {
            get
            {
                return this.OrganizationListField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OrganizationListField, value) != true))
                {
                    this.OrganizationListField = value;
                    this.RaisePropertyChanged("OrganizationList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyXFMOrganization.GeneralCriterion> SearchCriteria
        {
            get
            {
                return this.SearchCriteriaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SearchCriteriaField, value) != true))
                {
                    this.SearchCriteriaField = value;
                    this.RaisePropertyChanged("SearchCriteria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyXFMOrganization.SimpleCriterion> ListCriteria
        {
            get
            {
                return this.ListCriteriaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ListCriteriaField, value) != true))
                {
                    this.ListCriteriaField = value;
                    this.RaisePropertyChanged("ListCriteria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyXFMOrganization.OrganizationIdentity> IdentityCriteria
        {
            get
            {
                return this.IdentityCriteriaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.IdentityCriteriaField, value) != true))
                {
                    this.IdentityCriteriaField = value;
                    this.RaisePropertyChanged("IdentityCriteria");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Context", Namespace="http://www.tieto.com/cmw/tcm/")]
    public partial class Context : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string ClientRowVersionField;
        
        private System.Nullable<System.DateTime> CreatedDateField;
        
        private string ExtChannelIdField;
        
        private string ExtIdField;
        
        private string ExtPosReferenceField;
        
        private string ExtUserField;
        
        private string LanguageIdField;
        
        private System.Nullable<System.DateTime> RegDateField;
        
        private string RegInterfaceField;
        
        private System.Nullable<long> RegTokenField;
        
        private string RegUserField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ClientRowVersion
        {
            get
            {
                return this.ClientRowVersionField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ClientRowVersionField, value) != true))
                {
                    this.ClientRowVersionField = value;
                    this.RaisePropertyChanged("ClientRowVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<System.DateTime> CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                if ((this.CreatedDateField.Equals(value) != true))
                {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExtChannelId
        {
            get
            {
                return this.ExtChannelIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtChannelIdField, value) != true))
                {
                    this.ExtChannelIdField = value;
                    this.RaisePropertyChanged("ExtChannelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExtId
        {
            get
            {
                return this.ExtIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtIdField, value) != true))
                {
                    this.ExtIdField = value;
                    this.RaisePropertyChanged("ExtId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExtPosReference
        {
            get
            {
                return this.ExtPosReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtPosReferenceField, value) != true))
                {
                    this.ExtPosReferenceField = value;
                    this.RaisePropertyChanged("ExtPosReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExtUser
        {
            get
            {
                return this.ExtUserField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtUserField, value) != true))
                {
                    this.ExtUserField = value;
                    this.RaisePropertyChanged("ExtUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LanguageId
        {
            get
            {
                return this.LanguageIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LanguageIdField, value) != true))
                {
                    this.LanguageIdField = value;
                    this.RaisePropertyChanged("LanguageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<System.DateTime> RegDate
        {
            get
            {
                return this.RegDateField;
            }
            set
            {
                if ((this.RegDateField.Equals(value) != true))
                {
                    this.RegDateField = value;
                    this.RaisePropertyChanged("RegDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RegInterface
        {
            get
            {
                return this.RegInterfaceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.RegInterfaceField, value) != true))
                {
                    this.RegInterfaceField = value;
                    this.RaisePropertyChanged("RegInterface");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<long> RegToken
        {
            get
            {
                return this.RegTokenField;
            }
            set
            {
                if ((this.RegTokenField.Equals(value) != true))
                {
                    this.RegTokenField = value;
                    this.RaisePropertyChanged("RegToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RegUser
        {
            get
            {
                return this.RegUserField;
            }
            set
            {
                if ((object.ReferenceEquals(this.RegUserField, value) != true))
                {
                    this.RegUserField = value;
                    this.RaisePropertyChanged("RegUser");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CriteriaOptions", Namespace="http://www.tieto.com/cmw/tcm/organization")]
    public partial class CriteriaOptions : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private System.Nullable<bool> ShowActiveField;
        
        private System.Nullable<bool> ShowInactiveField;
        
        private System.Nullable<long> BrowseFromField;
        
        private System.Nullable<long> BrowseToField;
        
        private string SortFieldField;
        
        private string SortOrderField;
        
        private System.Nullable<bool> CaseSensitiveField;
        
        private string ExtPosReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<bool> ShowActive
        {
            get
            {
                return this.ShowActiveField;
            }
            set
            {
                if ((this.ShowActiveField.Equals(value) != true))
                {
                    this.ShowActiveField = value;
                    this.RaisePropertyChanged("ShowActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<bool> ShowInactive
        {
            get
            {
                return this.ShowInactiveField;
            }
            set
            {
                if ((this.ShowInactiveField.Equals(value) != true))
                {
                    this.ShowInactiveField = value;
                    this.RaisePropertyChanged("ShowInactive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Nullable<long> BrowseFrom
        {
            get
            {
                return this.BrowseFromField;
            }
            set
            {
                if ((this.BrowseFromField.Equals(value) != true))
                {
                    this.BrowseFromField = value;
                    this.RaisePropertyChanged("BrowseFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Nullable<long> BrowseTo
        {
            get
            {
                return this.BrowseToField;
            }
            set
            {
                if ((this.BrowseToField.Equals(value) != true))
                {
                    this.BrowseToField = value;
                    this.RaisePropertyChanged("BrowseTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SortField
        {
            get
            {
                return this.SortFieldField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SortFieldField, value) != true))
                {
                    this.SortFieldField = value;
                    this.RaisePropertyChanged("SortField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SortOrder
        {
            get
            {
                return this.SortOrderField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SortOrderField, value) != true))
                {
                    this.SortOrderField = value;
                    this.RaisePropertyChanged("SortOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public System.Nullable<bool> CaseSensitive
        {
            get
            {
                return this.CaseSensitiveField;
            }
            set
            {
                if ((this.CaseSensitiveField.Equals(value) != true))
                {
                    this.CaseSensitiveField = value;
                    this.RaisePropertyChanged("CaseSensitive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ExtPosReference
        {
            get
            {
                return this.ExtPosReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtPosReferenceField, value) != true))
                {
                    this.ExtPosReferenceField = value;
                    this.RaisePropertyChanged("ExtPosReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrganizationInfo", Namespace="http://www.tieto.com/cmw/tcm/organization")]
    public partial class OrganizationInfo : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private TCM.Web.Business.ProxyXFMOrganization.OrganizationIdentity IdentityField;
        
        private TCM.Web.Business.ProxyXFMOrganization.ObjectMetaData ObjectMetaDataField;
        
        private System.Nullable<bool> IsFundCompanyField;
        
        private System.Nullable<bool> IsDistributorField;
        
        private string ContactNameField;
        
        private string ContactPhoneField;
        
        private string ContactFaxField;
        
        private string ContactEmailField;
        
        private string OrderPlacementCodeField;
        
        private string OrderBICField;
        
        private string DistinguishedNameField;
        
        private string BankNameField;
        
        private string OrderPhoneField;
        
        private string OrderFaxField;
        
        private string OrderEmailField;
        
        private string DivisionNameField;
        
        private string AttentionField;
        
        private string CoAddressField;
        
        private string DistributionAddress1Field;
        
        private string DistributionAddress2Field;
        
        private string PostalCodeIdField;
        
        private string CityNameField;
        
        private string StateNameField;
        
        private string CountryIdField;
        
        private string CultureField;
        
        private System.Nullable<System.DateTime> EndDateField;
        
        private string ObjectVersionField;
        
        private string ExtPosReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TCM.Web.Business.ProxyXFMOrganization.OrganizationIdentity Identity
        {
            get
            {
                return this.IdentityField;
            }
            set
            {
                if ((object.ReferenceEquals(this.IdentityField, value) != true))
                {
                    this.IdentityField = value;
                    this.RaisePropertyChanged("Identity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TCM.Web.Business.ProxyXFMOrganization.ObjectMetaData ObjectMetaData
        {
            get
            {
                return this.ObjectMetaDataField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ObjectMetaDataField, value) != true))
                {
                    this.ObjectMetaDataField = value;
                    this.RaisePropertyChanged("ObjectMetaData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Nullable<bool> IsFundCompany
        {
            get
            {
                return this.IsFundCompanyField;
            }
            set
            {
                if ((this.IsFundCompanyField.Equals(value) != true))
                {
                    this.IsFundCompanyField = value;
                    this.RaisePropertyChanged("IsFundCompany");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Nullable<bool> IsDistributor
        {
            get
            {
                return this.IsDistributorField;
            }
            set
            {
                if ((this.IsDistributorField.Equals(value) != true))
                {
                    this.IsDistributorField = value;
                    this.RaisePropertyChanged("IsDistributor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ContactName
        {
            get
            {
                return this.ContactNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ContactNameField, value) != true))
                {
                    this.ContactNameField = value;
                    this.RaisePropertyChanged("ContactName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ContactPhone
        {
            get
            {
                return this.ContactPhoneField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ContactPhoneField, value) != true))
                {
                    this.ContactPhoneField = value;
                    this.RaisePropertyChanged("ContactPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ContactFax
        {
            get
            {
                return this.ContactFaxField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ContactFaxField, value) != true))
                {
                    this.ContactFaxField = value;
                    this.RaisePropertyChanged("ContactFax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ContactEmail
        {
            get
            {
                return this.ContactEmailField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ContactEmailField, value) != true))
                {
                    this.ContactEmailField = value;
                    this.RaisePropertyChanged("ContactEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string OrderPlacementCode
        {
            get
            {
                return this.OrderPlacementCodeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OrderPlacementCodeField, value) != true))
                {
                    this.OrderPlacementCodeField = value;
                    this.RaisePropertyChanged("OrderPlacementCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string OrderBIC
        {
            get
            {
                return this.OrderBICField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OrderBICField, value) != true))
                {
                    this.OrderBICField = value;
                    this.RaisePropertyChanged("OrderBIC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string DistinguishedName
        {
            get
            {
                return this.DistinguishedNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DistinguishedNameField, value) != true))
                {
                    this.DistinguishedNameField = value;
                    this.RaisePropertyChanged("DistinguishedName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string BankName
        {
            get
            {
                return this.BankNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.BankNameField, value) != true))
                {
                    this.BankNameField = value;
                    this.RaisePropertyChanged("BankName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string OrderPhone
        {
            get
            {
                return this.OrderPhoneField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OrderPhoneField, value) != true))
                {
                    this.OrderPhoneField = value;
                    this.RaisePropertyChanged("OrderPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string OrderFax
        {
            get
            {
                return this.OrderFaxField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OrderFaxField, value) != true))
                {
                    this.OrderFaxField = value;
                    this.RaisePropertyChanged("OrderFax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string OrderEmail
        {
            get
            {
                return this.OrderEmailField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OrderEmailField, value) != true))
                {
                    this.OrderEmailField = value;
                    this.RaisePropertyChanged("OrderEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string DivisionName
        {
            get
            {
                return this.DivisionNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DivisionNameField, value) != true))
                {
                    this.DivisionNameField = value;
                    this.RaisePropertyChanged("DivisionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Attention
        {
            get
            {
                return this.AttentionField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AttentionField, value) != true))
                {
                    this.AttentionField = value;
                    this.RaisePropertyChanged("Attention");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string CoAddress
        {
            get
            {
                return this.CoAddressField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CoAddressField, value) != true))
                {
                    this.CoAddressField = value;
                    this.RaisePropertyChanged("CoAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string DistributionAddress1
        {
            get
            {
                return this.DistributionAddress1Field;
            }
            set
            {
                if ((object.ReferenceEquals(this.DistributionAddress1Field, value) != true))
                {
                    this.DistributionAddress1Field = value;
                    this.RaisePropertyChanged("DistributionAddress1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string DistributionAddress2
        {
            get
            {
                return this.DistributionAddress2Field;
            }
            set
            {
                if ((object.ReferenceEquals(this.DistributionAddress2Field, value) != true))
                {
                    this.DistributionAddress2Field = value;
                    this.RaisePropertyChanged("DistributionAddress2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string PostalCodeId
        {
            get
            {
                return this.PostalCodeIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PostalCodeIdField, value) != true))
                {
                    this.PostalCodeIdField = value;
                    this.RaisePropertyChanged("PostalCodeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string CityName
        {
            get
            {
                return this.CityNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CityNameField, value) != true))
                {
                    this.CityNameField = value;
                    this.RaisePropertyChanged("CityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string StateName
        {
            get
            {
                return this.StateNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.StateNameField, value) != true))
                {
                    this.StateNameField = value;
                    this.RaisePropertyChanged("StateName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string CountryId
        {
            get
            {
                return this.CountryIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CountryIdField, value) != true))
                {
                    this.CountryIdField = value;
                    this.RaisePropertyChanged("CountryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string Culture
        {
            get
            {
                return this.CultureField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CultureField, value) != true))
                {
                    this.CultureField = value;
                    this.RaisePropertyChanged("Culture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public System.Nullable<System.DateTime> EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                if ((this.EndDateField.Equals(value) != true))
                {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string ObjectVersion
        {
            get
            {
                return this.ObjectVersionField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ObjectVersionField, value) != true))
                {
                    this.ObjectVersionField = value;
                    this.RaisePropertyChanged("ObjectVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string ExtPosReference
        {
            get
            {
                return this.ExtPosReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtPosReferenceField, value) != true))
                {
                    this.ExtPosReferenceField = value;
                    this.RaisePropertyChanged("ExtPosReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneralCriterion", Namespace="http://www.tieto.com/cmw/tcm/organization")]
    public partial class GeneralCriterion : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string SearchConcatenatorIdField;
        
        private string SearchFieldIdField;
        
        private string SearchOperatorIdField;
        
        private string SearchValueField;
        
        private string ExtPosReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SearchConcatenatorId
        {
            get
            {
                return this.SearchConcatenatorIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SearchConcatenatorIdField, value) != true))
                {
                    this.SearchConcatenatorIdField = value;
                    this.RaisePropertyChanged("SearchConcatenatorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SearchFieldId
        {
            get
            {
                return this.SearchFieldIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SearchFieldIdField, value) != true))
                {
                    this.SearchFieldIdField = value;
                    this.RaisePropertyChanged("SearchFieldId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SearchOperatorId
        {
            get
            {
                return this.SearchOperatorIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SearchOperatorIdField, value) != true))
                {
                    this.SearchOperatorIdField = value;
                    this.RaisePropertyChanged("SearchOperatorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SearchValue
        {
            get
            {
                return this.SearchValueField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SearchValueField, value) != true))
                {
                    this.SearchValueField = value;
                    this.RaisePropertyChanged("SearchValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ExtPosReference
        {
            get
            {
                return this.ExtPosReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtPosReferenceField, value) != true))
                {
                    this.ExtPosReferenceField = value;
                    this.RaisePropertyChanged("ExtPosReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SimpleCriterion", Namespace="http://www.tieto.com/cmw/tcm/organization")]
    public partial class SimpleCriterion : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string SearchFieldIdField;
        
        private string SearchValueField;
        
        private string ExtPosReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SearchFieldId
        {
            get
            {
                return this.SearchFieldIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SearchFieldIdField, value) != true))
                {
                    this.SearchFieldIdField = value;
                    this.RaisePropertyChanged("SearchFieldId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SearchValue
        {
            get
            {
                return this.SearchValueField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SearchValueField, value) != true))
                {
                    this.SearchValueField = value;
                    this.RaisePropertyChanged("SearchValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ExtPosReference
        {
            get
            {
                return this.ExtPosReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtPosReferenceField, value) != true))
                {
                    this.ExtPosReferenceField = value;
                    this.RaisePropertyChanged("ExtPosReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrganizationIdentity", Namespace="http://www.tieto.com/cmw/tcm/organization")]
    public partial class OrganizationIdentity : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private System.Nullable<int> OrganizationIdField;
        
        private string ExternalOrganizationIdField;
        
        private string NationalRegistrationIdField;
        
        private string OrganizationShortNameField;
        
        private string OrganizationNameField;
        
        private string ExtPosReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<int> OrganizationId
        {
            get
            {
                return this.OrganizationIdField;
            }
            set
            {
                if ((this.OrganizationIdField.Equals(value) != true))
                {
                    this.OrganizationIdField = value;
                    this.RaisePropertyChanged("OrganizationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ExternalOrganizationId
        {
            get
            {
                return this.ExternalOrganizationIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExternalOrganizationIdField, value) != true))
                {
                    this.ExternalOrganizationIdField = value;
                    this.RaisePropertyChanged("ExternalOrganizationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NationalRegistrationId
        {
            get
            {
                return this.NationalRegistrationIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NationalRegistrationIdField, value) != true))
                {
                    this.NationalRegistrationIdField = value;
                    this.RaisePropertyChanged("NationalRegistrationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string OrganizationShortName
        {
            get
            {
                return this.OrganizationShortNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OrganizationShortNameField, value) != true))
                {
                    this.OrganizationShortNameField = value;
                    this.RaisePropertyChanged("OrganizationShortName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string OrganizationName
        {
            get
            {
                return this.OrganizationNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OrganizationNameField, value) != true))
                {
                    this.OrganizationNameField = value;
                    this.RaisePropertyChanged("OrganizationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ExtPosReference
        {
            get
            {
                return this.ExtPosReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtPosReferenceField, value) != true))
                {
                    this.ExtPosReferenceField = value;
                    this.RaisePropertyChanged("ExtPosReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectMetaData", Namespace="http://www.tieto.com/cmw/tcm/organization")]
    public partial class ObjectMetaData : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private System.Nullable<System.DateTime> CreatedDateField;
        
        private string ExtChannelIdField;
        
        private string ExtUserField;
        
        private string ExtIdField;
        
        private string RegUserField;
        
        private System.Nullable<long> RegTokenField;
        
        private string RegInterfaceField;
        
        private System.Nullable<System.DateTime> RegDateField;
        
        private string ExtPosReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<System.DateTime> CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                if ((this.CreatedDateField.Equals(value) != true))
                {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExtChannelId
        {
            get
            {
                return this.ExtChannelIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtChannelIdField, value) != true))
                {
                    this.ExtChannelIdField = value;
                    this.RaisePropertyChanged("ExtChannelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExtUser
        {
            get
            {
                return this.ExtUserField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtUserField, value) != true))
                {
                    this.ExtUserField = value;
                    this.RaisePropertyChanged("ExtUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ExtId
        {
            get
            {
                return this.ExtIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtIdField, value) != true))
                {
                    this.ExtIdField = value;
                    this.RaisePropertyChanged("ExtId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string RegUser
        {
            get
            {
                return this.RegUserField;
            }
            set
            {
                if ((object.ReferenceEquals(this.RegUserField, value) != true))
                {
                    this.RegUserField = value;
                    this.RaisePropertyChanged("RegUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public System.Nullable<long> RegToken
        {
            get
            {
                return this.RegTokenField;
            }
            set
            {
                if ((this.RegTokenField.Equals(value) != true))
                {
                    this.RegTokenField = value;
                    this.RaisePropertyChanged("RegToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string RegInterface
        {
            get
            {
                return this.RegInterfaceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.RegInterfaceField, value) != true))
                {
                    this.RegInterfaceField = value;
                    this.RaisePropertyChanged("RegInterface");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public System.Nullable<System.DateTime> RegDate
        {
            get
            {
                return this.RegDateField;
            }
            set
            {
                if ((this.RegDateField.Equals(value) != true))
                {
                    this.RegDateField = value;
                    this.RaisePropertyChanged("RegDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ExtPosReference
        {
            get
            {
                return this.ExtPosReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtPosReferenceField, value) != true))
                {
                    this.ExtPosReferenceField = value;
                    this.RaisePropertyChanged("ExtPosReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrganizationRepositoryOutput", Namespace="http://www.tieto.com/cmw/tcm/organization")]
    public partial class OrganizationRepositoryOutput : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private bool SuccessField;
        
        private TCM.Web.Business.ProxyXFMOrganization.OrganizationRepository OrganizationRepositoryField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyXFMOrganization.Error> ErrorListField;
        
        private TCM.Web.Business.ProxyXFMOrganization.Context OutputContextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                if ((this.SuccessField.Equals(value) != true))
                {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public TCM.Web.Business.ProxyXFMOrganization.OrganizationRepository OrganizationRepository
        {
            get
            {
                return this.OrganizationRepositoryField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OrganizationRepositoryField, value) != true))
                {
                    this.OrganizationRepositoryField = value;
                    this.RaisePropertyChanged("OrganizationRepository");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyXFMOrganization.Error> ErrorList
        {
            get
            {
                return this.ErrorListField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorListField, value) != true))
                {
                    this.ErrorListField = value;
                    this.RaisePropertyChanged("ErrorList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public TCM.Web.Business.ProxyXFMOrganization.Context OutputContext
        {
            get
            {
                return this.OutputContextField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OutputContextField, value) != true))
                {
                    this.OutputContextField = value;
                    this.RaisePropertyChanged("OutputContext");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://www.tieto.com/cmw/tcm/")]
    public partial class Error : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string ErrorCodeField;
        
        private string ErrorMessageField;
        
        private string ExtErrorPosReferenceField;
        
        private string SystemErrorMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true))
                {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true))
                {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtErrorPosReference
        {
            get
            {
                return this.ExtErrorPosReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtErrorPosReferenceField, value) != true))
                {
                    this.ExtErrorPosReferenceField = value;
                    this.RaisePropertyChanged("ExtErrorPosReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SystemErrorMessage
        {
            get
            {
                return this.SystemErrorMessageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SystemErrorMessageField, value) != true))
                {
                    this.SystemErrorMessageField = value;
                    this.RaisePropertyChanged("SystemErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrganizationSaveSetInput", Namespace="http://www.tieto.com/cmw/tcm/organization")]
    public partial class OrganizationSaveSetInput : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private TCM.Web.Business.ProxyXFMOrganization.OrganizationSaveSet OrganizationSaveSetField;
        
        private TCM.Web.Business.ProxyXFMOrganization.Context InputContextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TCM.Web.Business.ProxyXFMOrganization.OrganizationSaveSet OrganizationSaveSet
        {
            get
            {
                return this.OrganizationSaveSetField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OrganizationSaveSetField, value) != true))
                {
                    this.OrganizationSaveSetField = value;
                    this.RaisePropertyChanged("OrganizationSaveSet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public TCM.Web.Business.ProxyXFMOrganization.Context InputContext
        {
            get
            {
                return this.InputContextField;
            }
            set
            {
                if ((object.ReferenceEquals(this.InputContextField, value) != true))
                {
                    this.InputContextField = value;
                    this.RaisePropertyChanged("InputContext");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrganizationSaveSet", Namespace="http://www.tieto.com/cmw/tcm/organization")]
    public partial class OrganizationSaveSet : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyXFMOrganization.OrganizationInfo> OrganizationListField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyXFMOrganization.OrganizationSaveResult> OrganizationResultListField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyXFMOrganization.OrganizationInfo> OrganizationList
        {
            get
            {
                return this.OrganizationListField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OrganizationListField, value) != true))
                {
                    this.OrganizationListField = value;
                    this.RaisePropertyChanged("OrganizationList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyXFMOrganization.OrganizationSaveResult> OrganizationResultList
        {
            get
            {
                return this.OrganizationResultListField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OrganizationResultListField, value) != true))
                {
                    this.OrganizationResultListField = value;
                    this.RaisePropertyChanged("OrganizationResultList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrganizationSaveResult", Namespace="http://www.tieto.com/cmw/tcm/organization")]
    public partial class OrganizationSaveResult : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private TCM.Web.Business.ProxyXFMOrganization.OrganizationIdentity IdentityField;
        
        private TCM.Web.Business.ProxyXFMOrganization.ObjectMetaData ObjectMetaDataField;
        
        private System.Nullable<bool> IsFundCompanyField;
        
        private System.Nullable<bool> IsDistributorField;
        
        private string ContactNameField;
        
        private string ContactPhoneField;
        
        private string ContactFaxField;
        
        private string ContactEmailField;
        
        private string OrderPlacementCodeField;
        
        private string OrderBICField;
        
        private string DistinguishedNameField;
        
        private string BankNameField;
        
        private string OrderPhoneField;
        
        private string OrderFaxField;
        
        private string OrderEmailField;
        
        private string DivisionNameField;
        
        private string AttentionField;
        
        private string CoAddressField;
        
        private string DistributionAddress1Field;
        
        private string DistributionAddress2Field;
        
        private string PostalCodeIdField;
        
        private string CityNameField;
        
        private string StateNameField;
        
        private string CountryIdField;
        
        private string CultureField;
        
        private System.Nullable<System.DateTime> EndDateField;
        
        private string ObjectVersionField;
        
        private string ActionCodeField;
        
        private System.Nullable<int> ErrorNumberField;
        
        private string ErrorTextField;
        
        private string ExtPosReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TCM.Web.Business.ProxyXFMOrganization.OrganizationIdentity Identity
        {
            get
            {
                return this.IdentityField;
            }
            set
            {
                if ((object.ReferenceEquals(this.IdentityField, value) != true))
                {
                    this.IdentityField = value;
                    this.RaisePropertyChanged("Identity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TCM.Web.Business.ProxyXFMOrganization.ObjectMetaData ObjectMetaData
        {
            get
            {
                return this.ObjectMetaDataField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ObjectMetaDataField, value) != true))
                {
                    this.ObjectMetaDataField = value;
                    this.RaisePropertyChanged("ObjectMetaData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Nullable<bool> IsFundCompany
        {
            get
            {
                return this.IsFundCompanyField;
            }
            set
            {
                if ((this.IsFundCompanyField.Equals(value) != true))
                {
                    this.IsFundCompanyField = value;
                    this.RaisePropertyChanged("IsFundCompany");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Nullable<bool> IsDistributor
        {
            get
            {
                return this.IsDistributorField;
            }
            set
            {
                if ((this.IsDistributorField.Equals(value) != true))
                {
                    this.IsDistributorField = value;
                    this.RaisePropertyChanged("IsDistributor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ContactName
        {
            get
            {
                return this.ContactNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ContactNameField, value) != true))
                {
                    this.ContactNameField = value;
                    this.RaisePropertyChanged("ContactName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ContactPhone
        {
            get
            {
                return this.ContactPhoneField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ContactPhoneField, value) != true))
                {
                    this.ContactPhoneField = value;
                    this.RaisePropertyChanged("ContactPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ContactFax
        {
            get
            {
                return this.ContactFaxField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ContactFaxField, value) != true))
                {
                    this.ContactFaxField = value;
                    this.RaisePropertyChanged("ContactFax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ContactEmail
        {
            get
            {
                return this.ContactEmailField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ContactEmailField, value) != true))
                {
                    this.ContactEmailField = value;
                    this.RaisePropertyChanged("ContactEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string OrderPlacementCode
        {
            get
            {
                return this.OrderPlacementCodeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OrderPlacementCodeField, value) != true))
                {
                    this.OrderPlacementCodeField = value;
                    this.RaisePropertyChanged("OrderPlacementCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string OrderBIC
        {
            get
            {
                return this.OrderBICField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OrderBICField, value) != true))
                {
                    this.OrderBICField = value;
                    this.RaisePropertyChanged("OrderBIC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string DistinguishedName
        {
            get
            {
                return this.DistinguishedNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DistinguishedNameField, value) != true))
                {
                    this.DistinguishedNameField = value;
                    this.RaisePropertyChanged("DistinguishedName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string BankName
        {
            get
            {
                return this.BankNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.BankNameField, value) != true))
                {
                    this.BankNameField = value;
                    this.RaisePropertyChanged("BankName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string OrderPhone
        {
            get
            {
                return this.OrderPhoneField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OrderPhoneField, value) != true))
                {
                    this.OrderPhoneField = value;
                    this.RaisePropertyChanged("OrderPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string OrderFax
        {
            get
            {
                return this.OrderFaxField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OrderFaxField, value) != true))
                {
                    this.OrderFaxField = value;
                    this.RaisePropertyChanged("OrderFax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string OrderEmail
        {
            get
            {
                return this.OrderEmailField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OrderEmailField, value) != true))
                {
                    this.OrderEmailField = value;
                    this.RaisePropertyChanged("OrderEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string DivisionName
        {
            get
            {
                return this.DivisionNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DivisionNameField, value) != true))
                {
                    this.DivisionNameField = value;
                    this.RaisePropertyChanged("DivisionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Attention
        {
            get
            {
                return this.AttentionField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AttentionField, value) != true))
                {
                    this.AttentionField = value;
                    this.RaisePropertyChanged("Attention");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string CoAddress
        {
            get
            {
                return this.CoAddressField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CoAddressField, value) != true))
                {
                    this.CoAddressField = value;
                    this.RaisePropertyChanged("CoAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string DistributionAddress1
        {
            get
            {
                return this.DistributionAddress1Field;
            }
            set
            {
                if ((object.ReferenceEquals(this.DistributionAddress1Field, value) != true))
                {
                    this.DistributionAddress1Field = value;
                    this.RaisePropertyChanged("DistributionAddress1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string DistributionAddress2
        {
            get
            {
                return this.DistributionAddress2Field;
            }
            set
            {
                if ((object.ReferenceEquals(this.DistributionAddress2Field, value) != true))
                {
                    this.DistributionAddress2Field = value;
                    this.RaisePropertyChanged("DistributionAddress2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string PostalCodeId
        {
            get
            {
                return this.PostalCodeIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PostalCodeIdField, value) != true))
                {
                    this.PostalCodeIdField = value;
                    this.RaisePropertyChanged("PostalCodeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string CityName
        {
            get
            {
                return this.CityNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CityNameField, value) != true))
                {
                    this.CityNameField = value;
                    this.RaisePropertyChanged("CityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string StateName
        {
            get
            {
                return this.StateNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.StateNameField, value) != true))
                {
                    this.StateNameField = value;
                    this.RaisePropertyChanged("StateName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string CountryId
        {
            get
            {
                return this.CountryIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CountryIdField, value) != true))
                {
                    this.CountryIdField = value;
                    this.RaisePropertyChanged("CountryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string Culture
        {
            get
            {
                return this.CultureField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CultureField, value) != true))
                {
                    this.CultureField = value;
                    this.RaisePropertyChanged("Culture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public System.Nullable<System.DateTime> EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                if ((this.EndDateField.Equals(value) != true))
                {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string ObjectVersion
        {
            get
            {
                return this.ObjectVersionField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ObjectVersionField, value) != true))
                {
                    this.ObjectVersionField = value;
                    this.RaisePropertyChanged("ObjectVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string ActionCode
        {
            get
            {
                return this.ActionCodeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ActionCodeField, value) != true))
                {
                    this.ActionCodeField = value;
                    this.RaisePropertyChanged("ActionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public System.Nullable<int> ErrorNumber
        {
            get
            {
                return this.ErrorNumberField;
            }
            set
            {
                if ((this.ErrorNumberField.Equals(value) != true))
                {
                    this.ErrorNumberField = value;
                    this.RaisePropertyChanged("ErrorNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string ErrorText
        {
            get
            {
                return this.ErrorTextField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorTextField, value) != true))
                {
                    this.ErrorTextField = value;
                    this.RaisePropertyChanged("ErrorText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public string ExtPosReference
        {
            get
            {
                return this.ExtPosReferenceField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExtPosReferenceField, value) != true))
                {
                    this.ExtPosReferenceField = value;
                    this.RaisePropertyChanged("ExtPosReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrganizationSaveSetOutput", Namespace="http://www.tieto.com/cmw/tcm/organization")]
    public partial class OrganizationSaveSetOutput : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private bool SuccessField;
        
        private TCM.Web.Business.ProxyXFMOrganization.OrganizationSaveSet OrganizationSaveSetField;
        
        private System.Collections.Generic.List<TCM.Web.Business.ProxyXFMOrganization.Error> ErrorListField;
        
        private TCM.Web.Business.ProxyXFMOrganization.Context OutputContextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                if ((this.SuccessField.Equals(value) != true))
                {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public TCM.Web.Business.ProxyXFMOrganization.OrganizationSaveSet OrganizationSaveSet
        {
            get
            {
                return this.OrganizationSaveSetField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OrganizationSaveSetField, value) != true))
                {
                    this.OrganizationSaveSetField = value;
                    this.RaisePropertyChanged("OrganizationSaveSet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Collections.Generic.List<TCM.Web.Business.ProxyXFMOrganization.Error> ErrorList
        {
            get
            {
                return this.ErrorListField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorListField, value) != true))
                {
                    this.ErrorListField = value;
                    this.RaisePropertyChanged("ErrorList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public TCM.Web.Business.ProxyXFMOrganization.Context OutputContext
        {
            get
            {
                return this.OutputContextField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OutputContextField, value) != true))
                {
                    this.OutputContextField = value;
                    this.RaisePropertyChanged("OutputContext");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.tieto.com/cmw/tcm/organization", ConfigurationName="TCM.Web.Business.ProxyXFMOrganization.IWSOrganization")]
    public interface IWSOrganization
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tieto.com/cmw/tcm/organization/IWSOrganization/Find", ReplyAction="http://www.tieto.com/cmw/tcm/organization/IWSOrganization/FindResponse")]
        System.Threading.Tasks.Task<TCM.Web.Business.ProxyXFMOrganization.OrganizationRepositoryOutput> FindAsync(TCM.Web.Business.ProxyXFMOrganization.OrganizationRepositoryInput inputDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tieto.com/cmw/tcm/organization/IWSOrganization/Save", ReplyAction="http://www.tieto.com/cmw/tcm/organization/IWSOrganization/SaveResponse")]
        System.Threading.Tasks.Task<TCM.Web.Business.ProxyXFMOrganization.OrganizationSaveSetOutput> SaveAsync(TCM.Web.Business.ProxyXFMOrganization.OrganizationSaveSetInput inputDTO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public interface IWSOrganizationChannel : TCM.Web.Business.ProxyXFMOrganization.IWSOrganization, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public partial class WSOrganizationClient : System.ServiceModel.ClientBase<TCM.Web.Business.ProxyXFMOrganization.IWSOrganization>, TCM.Web.Business.ProxyXFMOrganization.IWSOrganization
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSOrganizationClient() : 
                base(WSOrganizationClient.GetDefaultBinding(), WSOrganizationClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IWSOrganization.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSOrganizationClient(EndpointConfiguration endpointConfiguration) : 
                base(WSOrganizationClient.GetBindingForEndpoint(endpointConfiguration), WSOrganizationClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSOrganizationClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSOrganizationClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSOrganizationClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSOrganizationClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSOrganizationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<TCM.Web.Business.ProxyXFMOrganization.OrganizationRepositoryOutput> FindAsync(TCM.Web.Business.ProxyXFMOrganization.OrganizationRepositoryInput inputDTO)
        {
            return base.Channel.FindAsync(inputDTO);
        }
        
        public System.Threading.Tasks.Task<TCM.Web.Business.ProxyXFMOrganization.OrganizationSaveSetOutput> SaveAsync(TCM.Web.Business.ProxyXFMOrganization.OrganizationSaveSetInput inputDTO)
        {
            return base.Channel.SaveAsync(inputDTO);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWSOrganization))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWSOrganization))
            {
                return new System.ServiceModel.EndpointAddress("http://tcmrobur2012.bise.financialsolutions.se:801/WSOrganization.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WSOrganizationClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IWSOrganization);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WSOrganizationClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IWSOrganization);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IWSOrganization,
        }
    }
}
